### ISSUE TITLE
Failed gem dependency does not fail a check

### ISSUE THREAD

**Issue by jmccarty3** [sensu/sensu#1021]
I currently have a check that incorrectly defined a required file that was missing (copy/paste error). When sensu attempted to run the check, an exception was thrown from the ruby core, but the check is marked as a passing state.

Example 
CheckFile
```
require 'net/http'
require '<incorrect file>'
```

Sensu Output (Marked as passing in uchiwa):
```
/opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- <incorrect file> (LoadError) from /opt/sensu/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require' from
```

**Comment by shakycode** [comment]
Is this a ruby check you wrote or something from the sensu-community-plugin repo?  Either way it looks like you’re not handling errors properly in the script which is why it’s still passing an OK state.  Maybe something in your script is still reporting back a passing state?

If you can post your code I could take a look at it.

-James

**Comment by shakycode** [comment]
Is this a ruby check you wrote or something from the sensu-community-plugin repo?  Either way it looks like you’re not handling errors properly in the script which is why it’s still passing an OK state.  Maybe something in your script is still reporting back a passing state?

If you can post your code I could take a look at it.

**Comment by jmccarty3** [comment]
It was a check I wrote and was not handling that exception in the code. What I find confusing is that when that exception is thrown, the exit code is 3. Shouldn't the non-zero return code flag the check as at least not ok?

**Comment by portertech** [comment]
@jmccarty3 status 3 shows as an "unknown" and is displayed as such via the API/Dashboards, passed to event handlers.

**Comment by portertech** [comment]
This is not an issue w/ Sensu, as an exit 3 (unknown) is considered a non OK result, an event is created for the result and passed to event handlers as expected. It's up to the plugin to control which exit status is produced for an execution. Closing this issue.
