### ISSUE TITLE
Need some advice on setting up occurrences.

### ISSUE THREAD

**Issue by tleung999** [sensu/sensu#1092]
Hi there,

I have a sensu check that would use an email handler on CRITICAL and OK states.   When I don't specify occurrences, it would trigger the first time something hits critical and triggers when things "recover" and goes back to normal.  This is working good.

I wanted to change the check so that after 5 checks (1 min per check) it will send an email saying something is in CRITICAL state, and after it drops back to OK state I wanted it to send the recover email.   My problem now is that the 5 CRITICAL checks triggers the email, but when it goes back down to OK state, I no longer get an email trigger.   I also have a Slack check that is also not posting recovery messages now.   What is the best way to solve this?

My check looks like this

```
{
  "checks": {
    "check-sidekiq-queue": {
      "handlers": ["default", "mailer", "slack"],
      "occurrences": 5,
      "command": "/etc/sensu/plugins/check-sidekiq-queue.rb",
      "interval": 60,
      "subscribers": [ "check_sidekiq_queue" ]
    }
  }
}
```

My mailer configuration

```
{
  "handlers": {
    "mailer": {
      "type": "pipe",
      "command": "/etc/sensu/handlers/mailer.rb",
      "severities": [
        "critical",
        "ok"
      ]
    }
  }
}
```

**Comment by portertech** [comment]
@tleung999 does the Sensu server log `/var/log/sensu/sensu-server.log` provide any hints to as why the resolve action is not sending an email?

**Comment by petere** [comment]
I have observed something lately that might be related. The problem is that the event will only resolve when the handler has received consecutive "OK" results equal to the "occurrences" setting.  So in your case it needs 5 OK results before it resolves.  But it appears that the client will only send one OK result and then not send anything more until the state changes again.  So in other words, if this is correct, it's broken.  I'm pretty sure this used to work somehow at some point, so it might be a recent change, perhaps in the sensu-plugins module.

**Comment by petere** [comment]
I happened to find another check where the resolution works, in spite of the observation described above.  This particular check has occurrences set to 2.  Some interesting pieces of the message are:

```
"status":0,"history":["0","0","0","0","0","0","0","0","0","0","0","0","0","0","0","2","2","2","2","2","0"],"total_state_change":11},"occurrences":5,"action":"resolve"}}
```

Note that the message says `"occurrences": 5`.  Apparently, the occurrences count does not get reset when the status changes to 0. (Why?) As a consequence, the handler is happy to resolve the incident, because 5 > 2.

The other check I referred to above has occurrences set to 5.  The interesting parts of the message are

```
"status":0,"history":["0","0","0","0","0","0","0","0","0","0","0","0","1","1","2","2","2","2","2","1","0"],"total_state_change":22},"occurrences":1,"action":"resolve"}}
```

Apparently, because the state changed from critical to warning just before resolving, the occurrences were reset to 1 and are then never updated afterwards, as described above.

You didn't indicate that your check could issue warning results, so I don't know if this actually matches your scenario. But I'm coming around to the conclusion that the occurrences stuff is pretty shaky.  (See also debate in #885 about what occurrences actually mean for flapping checks.)

**Comment by calebhailey** [comment]
I wonder if we can close this now? We've made a number of [improvements around occurrence filtering](https://github.com/sensu/sensu-extensions/pull/11), including a PR that [specifically addressed issues related to resolutions](https://github.com/sensu-extensions/sensu-extensions-occurrences/pull/2). 

Barring any new updates to this issue indicating otherwise, we will look to close this issue due to inactivity at our next issue triage. :v:

**Comment by majormoses** [comment]
Could it be a flapping event? If so then the handler needs to be configured to handle flapping events and the handler must actually support this. I recently saw something similar in the pagerduty handler but patched it to support this behavior: https://github.com/sensu-plugins/sensu-plugins-pagerduty/pull/41

**Comment by portertech** [comment]
Closing, as we have made several improvements to occurrence/refresh filtering, including moving it into core as built-in filters.

Please reopen this issue if it is still an issue!
