### ISSUE TITLE
sensu debian package doesn't restart service on upgrade

### ISSUE THREAD

**Issue by br0ch0n** [sensu/sensu#1147]
Please see https://github.com/sensu/uchiwa/issues/428 for details.   Thanks!

**Comment by calebhailey** [comment]
This is by design; see here for more information: https://sensuapp.org/docs/latest/install-sensu-client#disabled-by-default (this applies to all of the Sensu processes). The Sensu packages will never do service management, however they will always provide the necessary service scripts to enable operators to manage its services. 

See the new [Sensu on Ubuntu/Debian](https://sensuapp.org/docs/0.23/sensu-on-ubuntu-debian) documentation for more information.
