### ISSUE TITLE
Not able to see newly posted message in the list of clients

### ISSUE THREAD

**Issue by Srungaram** [sensu/sensu#1158]
I am posting data from kapacitor to sensu and below is the log that confirms that
{"timestamp":"2016-01-28T15:24:40.169184-0500","level":"info","message":"POST /","remote_address":"127.0.0.1","user_agent":"Go-http-client/1.1","request_method":"POST",
"request_uri":"/","request_body":"{\"name\":\"measurement.name:nil\",\"output\":\"measurement.name:nil is CRITICAL\",\"source\":\"Kapacitor\",\"status\":2}\n"}

I am trying to check the new client at localhost:4567 and I dont see the above client. When I list the clients I am able to see only my test client i-424242. Please help on this.

**Comment by calebhailey** [comment]
@Srungaram it looks like you're attempting to POST to a non-existing API endpoint (i.e. the "root" `/` uri). This doesn't look like an issue with Sensu itself, but please feel free to open a new issue if you can provide some additional context to prove otherwise. 

Also, if you need help learning Sensu, please consider [Sensu Training](https://sensuapp.org/training), or try hanging out in the #sensu Freenode channel - there are usually many Sensu users there who can help.

#monitoringlove
