### ISSUE TITLE
Event is filtered before running mutator

### ISSUE THREAD

**Issue by kobbe** [sensu/sensu#1175]
I interpreted the documentation that a mutator is run before a filter: "Sensu mutators mutate (transform) event data for a Sensu event handler". This is not the case of what I have discovered. Is this intended? 

I want to use a mutator before filtering for a even more advanced filtering than only comparing a single field with a static value `eval: value == 3`. Using a mutator I can (should) combine several fields such that they for example match and then filter on the result.

I noticed this by the fact that the mutator is not even run if the filter filters out the event.

I am running sensu 0.21

**Comment by dmsimard** [comment]
Funny that you mention that, I am trying to do exactly the same thing - merge keys into a single key for usage in a filter. I talked about my use case on the [mailing list](https://groups.google.com/forum/#!topic/sensu-users/R6mybvXV5A0) and gave up trying to hack filter.rb to do what I want it to do and tried a mutator instead.

I added a file creation right in the mutator to be *certain* when it would run and no files are created unless the filter returns "true"
Example script: https://gist.github.com/dmsimard/bd49f7ec459e66ec7b94

My understanding is the same as yours as far as the flow is concerned:

    check -> event -> [mutator if exists] -> [filter if exists] -> [handler if exists]

I can tell the filter runs all the time (since I hacked something right within filter.rb to create a debug file each time it is used) but I come to the same conclusion as you, it looks like the flow is instead:

    check -> event -> filter -> mutator -> handler

Because the mutator seems to only be run if the filter returns true.

**Comment by dmsimard** [comment]
Looks like the mutator is indeed run after the filter: https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L212

So I guess this is not a bug, however, it would make more sense to run the mutator before the filter...

I'll hack some more on this later.

**Comment by dmsimard** [comment]
So I got the mutator to run before the filter and also confirmed that the mutated event (i.e, with an extra key) is indeed sent to the filter.

Here's the hack that I needed (don't try this at home, not responsible if it breaks things, yadda yadda)

    --- process.rb_before	2016-01-29 20:34:00.000000000 +0000
    +++ process.rb_after	2016-02-29 16:04:32.921980816 +0000
    @@ -2,6 +2,7 @@
     require "sensu/server/filter"
     require "sensu/server/mutate"
     require "sensu/server/handle"
    +require "json"
     
     module Sensu
       module Server
    @@ -224,8 +225,9 @@
             handlers = derive_handlers(handler_list)
             handlers.each do |handler|
               @handling_event_count += 1
    -          filter_event(handler, event) do |event|
    -            mutate_event(handler, event) do |event_data|
    +          mutate_event(handler, event) do |event|
    +            event = JSON.parse(event,:symbolize_names => true)
    +            filter_event(handler, event) do |event_data|
                   handle_event(handler, event_data)
                 end
               end

The tricky part is that filter_event expects a ruby hash (with keys as symbols) but mutate_event returns a JSON "string" - so it was necessary to translate that string back into a hash with symbols as keys with JSON.parse.

@Sensu developers: I don't think the above is a good fix (just a hack as a proof of concept in my case), but I'm convinced it makes sense that mutators should run before filters.

**Comment by kobbe** [comment]
I am not totally convinced that mutators should run before filters all the time since #1136 says that mutators are quite expensive to run. A better fix would probably be that a handler can choose the order itself. The most important thing is that the documentation is clear.

**Comment by dmsimard** [comment]
@kobbe agreed. Perhaps a way of setting a mutator on a filter ? RIght now mutator is a handler parameter. It could be a filter parameter as well.

**Comment by portertech** [comment]
@kobbe @dmsimard Also, filters operate with the assumption that the event data is still a hash.

**Comment by portertech** [comment]
And why mutate data when the event is going to be filtered anyways.

**Comment by kobbe** [comment]
As I said before, I need to combine several attributes of a check to make the filtering more complex.

My example is that I want to filter email handlers to only email me once every 24hrs if the problem still occurs. For some checks this is occurences % 60 and on others it is occurences % 24 etc. Doing this manually is a pain in the ass, I need 1 new filter and handler for each different occurences % n I want to have and all checks have to use different handlers. This easily becomes a mess after a while and using duplicated code is never neat.

Doing this with a mutator would mean that I can add a field in the check that is the % n value and only needing one handler and one filter in total.

The solution I would want is that filters could be applied before and after mutators.

**Comment by dmsimard** [comment]
@portertech My use case is similar to Kobbe: being able to do advanced filtering on multiple keys instead of being restricted to one. i.e, filter the value of the event occurrences against the value of the check occurrences. Managing "notification" (handler execution) interval out of the box in Sensu is awkward and non-intuitive with the occurrences, refresh and interval parameters.

This said, in the meantime, the helpful guys at Yelp pointed me in the direction of Sensu extensions that can be used as a filter inside the statemachine.
They have really taken the "notification" logic out of sensu and into [entirely custom handlers](https://github.com/Yelp/sensu_handlers). This is IMO, a testament that there are very significant gap in how to properly manage things like notifications and their intervals.

Anyway, with their help, I was able to come up with exactly just what I needed -- a filter to compare the check occurrences against the event occurrences and even a custom parameter - retry_occurrences. Gist here: https://gist.github.com/dmsimard/88ae4882033240a36088

@kobbe I think that gist can help you get to where you want.
You just have to drop the .rb file in /etc/sensu/extensions and then in the handler use the "name" of the extension (i.e, "check_retry_occurrences" in this case) as one of the filters.

**Comment by calebhailey** [comment]
@kobbe: first off, thank you for submitting this issue, and for your follow-up comments & examples. I agree that "The most important thing is that the documentation is clear", which could clearly use some improvement to have made it more obvious that filters are processed before mutators and handlers. We _have_ recently made some improvements in this regard, but perhaps not obviously enough (see: [Sensu Monitoring Flow](https://sensuapp.org/docs/latest/architecture#the-sensu-monitoring-flow), which was just recently published along with other [improvements to the documentation overview page](https://github.com/sensu/sensu-docs/pull/320)). 

> "The most important thing is that the documentation is clear"

Having said that, even if the documentation was better, it is also clear that Filters are somewhat limited in their ability to `eval` event data (i.e. limiting evaluations to a single `value > 60`). As you clearly explained, if you "need to combine several attributes of a check" today, it's not currently possible without writing a custom plugin or extension, which is unfortunate.

@dmsimard thanks for your time on Freenode#sensu today, and for bringing this issue to my attention. We have had some Filtering improvements on the backlog for some time now, but this issue has helped us finally settle on a solution we think will address the majority of the examples mentioned in this PR (and in our conversation on Freenode), including "being able to do advanced filtering on multiple keys instead of being restricted to one". 

## Adding support for Filter `eval` token substitution

After some internal discussion with @portertech, we are proposing to implement support for Filter `eval` token substitution (similar to how [check command tokens](https://sensuapp.org/docs/latest/checks#check-command-tokens) work). To do so, we would add support for a new `eval` Filter definition attribute, with new support for `eval` token substitution. Here's an example:

```
"filters": {
  "example_filter": {
    "eval": ":::occurrences::: > :::check.occurrences:::"
  }
}
```

This example is comparing event `occurrences` against the occurrence threshold as defined in the check definition. 

### Notes 

- The default `eval` token "scope" is event attributes, so `:::occurrences:::` will return the `occurrence` value from the event, whereas `:::check.occurrences:::` will return the `occurrence` attribute value from the check definition. 

- Available `eval` scopes: 
  - `check`
  - `client`

- Example `eval` values: 
  - `:::check.attribute:::`
  - `:::check.attribute.foo:::`
  - `:::client.attribute:::`

- New eval token substitution may be used alongside filter attribute matchers; e.g.:  

  ```
  "filters": {
    "example_filter": {
      "eval": ":::occurrences::: > :::check.occurrences:::",
      "attributes": {
        "environment": "production"
      }
    }
  }
  ```

**Comment by kobbe** [comment]
@calebhailey That sounds great and would work perfectly. I think it is much neater than changing the values in a mutator too since it requires less configuration files.

That documentation does it but consider changing the wording in the mutator docs to something less ambiguous or add that a mutator runs after a filter.

Thank you :+1:

**Comment by calebhailey** [comment]
@kobbe awesome; thanks for your feedback! We are _super tentatively_ hoping to sneak this into the impending 0.23 release (which is primarily going to be about native support for [Redis Sentinel](https://github.com/sensu/sensu-redis)), but no promises. :) Worst case scenario, we can definitely implement this in 0.24, which are already planning to come right on the heels of 0.23. :) 

/cc @portertech

**Comment by kobbe** [comment]
@portertech Close now?

**Comment by calebhailey** [comment]
@kobbe I still have to ship docs for this, but I should get those out before the end of the week. I'll go ahead and close this now! \o/ 

In the interim, please note that the actual implementation ended up a bit differently than what I suggested in my previous comment. We did not end up adding a key called `eval`; instead, filter attribute eval works exactly like it did before with the addition of token substitution. In other words, you still use the `eval:` keyword to declare an eval statement, but that statement can now include tokens. Here's an example: 

```
"filters": {
  "example_filter": {
    "attributes": {
      "occurrences": "eval: value > :::check.occurrences|60:::",
      "environment": "production"
    }
  }
}
```

As you can see, the `value` attribute is still available, and it can be compared against any other attribute. 

For comparing multiple values, we're considering suggesting a pattern like this: 

```
"filters": {
  "example_filter": {
    "attributes": {
      "eval": "eval: :::occurrences::: > :::check.occurrences|60:::",
      "environment": "production"
    }
  }
}

```

In this case I'm using "eval" as a fake attribute and then not using the `value` attribute, because that attribute would obviously not exist in my check result. I hope that makes sense. Let me know if you have any questions. 

/cc @dmsimard 

#monitoringlove
