### ISSUE TITLE
Aggregate for standalone checks

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1187]
Please add support aggreation support for standalone checks. This should be quite easy, in order to synchronize the check start time, you could hash the checkname and build a common start time.

For example checks which a running each minute
check_a => hash => 10 (first start 00:00:10, next start 00:01:10, ...)
check_b => hash => 30
check_c => hash => 59

**Comment by calebhailey** [comment]
This might already "just work" if you set `"standalone": true` in a standalone check definition, because the standalone scheduler uses the same algorithm for execution requests (see: https://sensuapp.org/docs/latest/clients#standalone-check-execution-scheduler). Having said that, minor differences in system clocks between disparate Sensu clients may result in standalone check results being grouped into multiple aggregates. 

/cc @agoddard

**Comment by runningman84** [comment]
Yes I have tried it but id did not work. Even though my clients use ntp I still got different start time for the checks and aggregation with only one value.

For example:

Check every 60s using 3 clients

05 client 1 check run
06 server builds aggregate (count 1)
16 client 2 check run
17 server builds aggregate (count 1)
30 client 3 check run
31 server builds aggregate (count 1)

**Comment by roobert** [comment]
In case it's helpful, I wrote a patch to do this a while ago but it was considered too-complicated a merge: https://github.com/sensu/sensu/pull/915/files

**Comment by calebhailey** [comment]
@runningman84 thanks for your update; @roobert thanks for your contribution as well. I know this is on the short list of things @portertech wants to improve in the near future, so stay tuned for some updates on this.

**Comment by calebhailey** [comment]
A proposal for "aggregates 2.0" has been published as a comment on issue #1218. Barring any objections, this proposal will be implemented in Sensu 0.24 which will resolve this issue.

**Comment by portertech** [comment]
Aggregates 2.0 has been merged into the release/0.24 branch #1273 Sensu 0.24 will be available sometime next week.
