### ISSUE TITLE
different refresh intervals for warning and critical events

### ISSUE THREAD

**Issue by joshzitting** [sensu/sensu#1223]
Does anyone else have a use case for different refresh intervals for warning and critical events?
For example.. If my disk is at 85% (warning) it will probably be ok till the morning and thus send a reminder (handle the event) every few hours.. But if it is 90% it is critical and should remind us every 30 minutes until it has been resolved?

With nagios you had to do this with service escalations.. But it seems like it could be done way easier in the check definitions? 
The other way I maybe could do this is in a filter have a fairly complex filter? 
We are using hipchat and just some mailer handlers.. so nothing cool like pagerduty to do the work for us.. 
Thanks!

**Comment by calebhailey** [comment]
You should be able to accomplish this with a filter. I'll try to help with an example tomorrow. :smile:

**Comment by calebhailey** [comment]
@joshzitting hi there. :wave: 

Sorry I couldn't follow-up yesterday... so, you _can_ accomplish this using a filter. What you'd want to do is setup the check to be executed at the more frequent interval (e.g. 30 minutes), and then use a filter to control the flow of notifications and/or handlers. Here's some pseudo-code (pseudo-configuration?) examples: 

#### Example check definition

`/etc/sensu/conf.d/example_check.json`

~~~ json
{
  "checks": {
    "example_check": {
      "command": "do_something.rb -o option",
      "interval": 1800,
      "subscribers": [
        "production"
      ],
      "handlers": [
        "example_handler"
      ]
    }
  }
}
~~~ 

This example [check](https://sensuapp.org/docs/latest/checks) is configured to use the `example_handler` [event handler](https://sensuapp.org/docs/latest/handlers). 

#### Example handler definition 

`/etc/sensu/conf.d/example_handler.json`

~~~ json
{
  "handlers": {
    "example_handler": {
      "type": "pipe",
      "command": "send_a_notification.rb",
      "filters": [
        "example_filter"
      ]
    }
  }
}
~~~

This example handler is configured to use the `example_filter` [event filter](https://sensuapp.org/docs/latest/filters). 

#### Example filter definition

`/etc/sensu/conf.d/example_filter.json`

~~~ json
{
  "filters": {
    "example_filter": {
      "negate": true,
      "attributes": {
        "status": 1,
        "occurrences": "eval: value != 1 || value % 6 != 0",
        "check": {
          "interval": 1800
        }
      }
    }
  }
}
~~~

This [filter](https://sensuapp.org/docs/latest/filters) is configured to `negate` any events that are `warning` status, that are not the first or every 6th event, and that have a check interval of 1800 (every 30  minutes, thus making "every 6th event" equivalent of every 3 hours). If all three of those conditions are _not_ matches, this filter won't prevent handling (i.e. all of the conditions need to be met for this filter to prevent the `example_handler` from firing). 

NOTE: 
- When handling a critical event, this filter won't prevent handling because it doesn't match `"status": 1`
- When handling any event with an interval other than `1800`, this filter won't match (e.g. it won't apply to events with a 30 second interval)
- Filters can be configured so that they only apply to events from specific checks, specific subscriptions, or specific clients
- Filters can be shared between handlers, so a single filter definition can be used with multiple handlers (e.g. if your check has an "email" and "Slack" handler, you could apply to the filter to the email handler _and_ Slack; or you could only apply it to the email handler and allow the Slack handler to fire on every event) 

I hope this helps! I'll wait for your reply before I close this. 

PS- if you need help learning Sensu, please consider [Sensu Training](https://sensuapp.org/training). :) 

#monitoringlove 

-cH

**Comment by joshzitting** [comment]
Cool thanks. I'll give it a try.

**Comment by calebhailey** [comment]
@joshzitting I'm going to go ahead and close this issue now. Please feel free to comment if this matter is not resolved.
