### ISSUE TITLE
'connect_server': unable to resolve server address

### ISSUE THREAD

**Issue by lukyanov** [sensu/sensu#1275]
When the host with RabbitMQ does not exist at the moment when sensu-client is starting, the client fails with the error:

```
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:677:in `connect_server': unable to resolve server address: Inappropriate ioctl for device (EventMachine::ConnectionError)
```

The version of sensu I use is 0.23.2.

rabbitmq.json:

```
{
  "rabbitmq": {
    "ssl": {
      "cert_chain_file": "/etc/sensu/ssl/cert.pem",
      "private_key_file": "/etc/sensu/ssl/key.pem"
    },
    "host": "server.domain.com",
    "port": 5671,
    "vhost": "/sensu",
    "user": "sensu",
    "password": "sensu"
  }
}
```

The issue is that server.domain.com is not resolvable at all when the client starts.

The full use case see here: https://github.com/sensu/sensu/issues/1270

**Comment by okushchenko** [comment]
I can confirm this issue on 23.2 version of Sensu. I am using Consul for service discovery and Sensu transport is configured as a DNS record, so Sensu Server doesn't reresolve DNS when it is unable to resolve it during the first attempt. Moreover, Sensu Server just keeps running without exiting correctly when this issue is encountered.

**Comment by calebhailey** [comment]
Closing in favor of https://github.com/sensu/sensu-transport/issues/39
