### ISSUE TITLE
Distribute scheduled checks evenly among the check interval

### ISSUE THREAD

**Issue by nhooey** [sensu/sensu#1297]
Currently if a check is scheduled every minute or hour, the check is scheduled on the minute or hour for every Sensu client node. This leads to spikes in RabbitMQ messages, and spikes in activity on every Sensu client node.

Having the checks scheduled evenly across the interval, using a hash of the Sensu client's name as a modulus, would evenly distribute this activity.

**Comment by nheinemans** [comment]
I would love to see this feature added, the scheduled checks are causing spikes on our platform which could easily be levelled out by spreading the checks throughout the interval.

**Comment by calebhailey** [comment]
Giving this the feature label as part of an ongoing triage for consideration in a future release. 

There are a few other scheduler enhancements we've been talking about squeezing in before Sensu Core hits 1.0 later this summer, so this could be considered in the near future.

**Comment by portertech** [comment]
Due to Sensu's use of the fanout topology for check request publishing, this is not possible. You can use standalone checks for a natural and irregular distribution, or a round-robin subscription with a very low interval. Several of Sensu's features rely on this concurrent check execution model, such as named aggregates.
