### ISSUE TITLE
TTL check has a different interval from the original check

### ISSUE THREAD

**Issue by lp0** [sensu/sensu#1302]
If I have a check running every 5 minutes and the TTL expires on the last result, sensu starts calling the handler every 30 seconds but the check will not recover until the next 5 minute interval.

The message to the handler also increments the number of occurrences every 30 seconds which makes it impossible for the handler to identify the duration of that state or correctly determine the duration when the check is resolved.

Delaying an alert based on the number of occurrences fails to work properly because the number of occurrences goes up rapidly.

**Comment by calebhailey** [comment]
@lp0 thank you for submitting this issue! This is an interesting problem indeed. There are a few other TTL-related issues that we're taking a look at in the upcoming 0.26 release (e.g. #1282). 

@portertech perhaps we should have the Sensu server compare the `ttl` and `interval` values during [`determine_stale_check_results`](https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L862-L891)? I'm not sure if we store enough state (i.e. the time of the last TTL event) in order to be able to compare it against the check `interval` currently, but that doesn't seem too unreasonable to me.

**Comment by portertech** [comment]
Without a 30 second TTL event update, the time since last check result information will be incorrect/outdated.

**Comment by CVTJNII** [comment]
Suggest altering the interval in the message so that the handlers, which by default use refresh and interval to calculate the count to alert at, will automatically update for the interval change.  This should mitigate the problem when using the sensu-plugins handler, though it's a bit of a hack.

Ref: https://github.com/sensu-plugins/sensu-plugin/blob/master/lib/sensu-handler.rb#L171

**Comment by portertech** [comment]
The check TTL override is available in Sensu >= 0.27.0 :+1:
