### ISSUE TITLE
Deregistration stopped working

### ISSUE THREAD

**Issue by blakebarnett** [sensu/sensu#1430]
## Expected Behavior

We've been using the built-in deregistration for a while now without problems, but recently we have been seeing a lot of them fail.  
## Current Behavior

The events show up and the output says "client initiated deregistration" but they never happen, keepalives fail as well.  They sit there forever.
## Steps to Reproduce (for bugs)

Just stop a client.
## Context

We have a large build up of stale clients and deregistration events when we do deployments, and have to purge them manually.
## Your Environment
- Sensu version used: 0.25.7
- Operating System and version (e.g. Ubuntu 14.04): Ubuntu 14.04
- Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): redis (AWS ElastiCache)

**Comment by kyle-long** [comment]
I seem to be experiencing the same problem unless I am misunderstanding how deregistration works. Could somebody confirm this one way or another?

**Comment by jaykumar-jnpr** [comment]
Can you confirm health status of sensu-api?

I encountered the same issue in the past, but found the sensu-api was not reachable.

**Comment by kyle-long** [comment]
The messages are being consumed. I can see the event being added via uchiwa (unless I am mistaken about how this process works). It simply doesn't do anything about it.

**Comment by jaykumar-jnpr** [comment]
Ok so if I am not wrong, this is how registration works.

Sensu client creates a deregistration event ==> Sensu server + Deregistration Handler call ==> Sensu API to delete the Client from Inventory.

You are seeing the event on uchiwa because deregistration events are being successfully created, but somehow failed to be process at handler or API level. 

Couple of test I would do.

1. Check the Sensu server logs for deregistration events and handler logs
2. Can you delete clients (once client is shutdown) from Uchiwa. This would confirm API call are working fine.
3. I don't remember exactly but after some specific Sensu version, the client require "deregister:true" parameter. Do you have it configured on Sensu client?

**Comment by kyle-long** [comment]
1. It appears sensu server logs the deregister event

```
{"timestamp":"2016-11-04T19:21:43.883946+0000","level":"info","message":"processing event","event":{"id":"2af27131-b9a4-4425-94b6-64e97258d983","client":{"name":"haproxy-xxx-xxx-xx-xxx","address":"localhost","deregister":true,"deregistration":{"handler":"deregister_client"},"subscriptions":["Linux","Sensu-Client","client:haproxy-xxx-xxx-xx-xxx"],"XXX":{"tags":""},"version":"0.26.5","timestamp":1478287293},"check":{"handler":"deregister_client","interval":1,"name":"deregistration","output":"client initiated deregistration","status":1,"issued":1478287303,"executed":1478287303,"history":["1"],"total_state_change":0},"occurrences":1,"action":"create","timestamp":1478287303}}
```
With a few things redacted.

2. I can.
3. Yes, I have it configured in the client.json file

```
...
    "deregister": true,
    "deregistration": {
        "handler": "deregister_client"
    },
...
```

**Comment by kyle-long** [comment]
Oh my, I was so concerned with what the clients version was I hadn't checked the server which is still running `0.21.0`. The deregister configuration options were added in `0.25.0` https://sensuapp.org/docs/0.25/overview/changelog.html#core-v0-25-0-changes. I would imagine the server was updated to handle these events around the same time?

**Comment by cwjohnston** [comment]
@kyle-long the server doesn't need any explicit support for deregistration, but you do need a "deregister_client" handler configured. We added [a handler to the sensu-plugins-sensu project]( https://github.com/sensu-plugins/sensu-plugins-sensu/blob/master/bin/handler-sensu-deregister.rb) around the time of this release.

Do you have such a handler configured? Is there a log entry showing that handler being executed?

**Comment by kyle-long** [comment]
@cwjohnston Yes

```
...
    "deregister": true,
    "deregistration": {
        "handler": "deregister_client"
    },
...
```

My understanding was that this client was built into sensu now. Was this a bad assumption? At least that is the way I was reading the changelog here https://sensuapp.org/docs/0.25/overview/changelog.html#core-v0-25-0-changes.

**Comment by cwjohnston** [comment]
@kyle-long the deregsitration handler plugin I linked to previously is not built into the server and there's no default handler definition for the "deregister_client". This may seem counter-intuitive, and I can understand why. The intent is to allow operators to compose a deregistration flow that makes sense for their needs.

For example, some organizations may want a deregistration event to simply remove the client from the Sensu registry, while others may want to send the deregistration event to multiple handlers so that one deregistration event triggers multiple actions (e.g. remove client from Sensu registry and open/close a ticket via an external service api, etc).

From the log entries you've provided it is clear that your server is receiving a deregistration event from the client. In order for your server to take action on these events, I recommend the following steps:

1. [Install](https://sensuapp.org/docs/0.26/reference/plugins.html#installing-sensu-plugins) handler-deregister-sensu.rb from [sensu-plugins-sensu](https://github.com/sensu-plugins/sensu-plugins-sensu/) gem.
2. Create a [pipe handler definition](https://sensuapp.org/docs/0.26/reference/handlers.html#pipe-handlers) on the server matching the handler name "deregister_client". This handler definition should specify "handler-deregister-sensu.rb" as its command.
3. Restart the sensu-server process to ensure the new handler configuration is loaded

Once you have completed these steps, client deregistration events with the handler "deregister_client" should cause the handler-deregister-sensu.rb handler plugin to be executed, which will use the API to delete the client from the Sensu registry.

**Comment by kyle-long** [comment]
@cwjohnston Great thank you! I won't be able to verify this works until I am given additional time to work on it but this certainly cleared up my confusion!

**Comment by calebhailey** [comment]
@blakebarnett I'm curious if this issue was resolved via @cwjohnston's comments/clarification, above, as we're not seeing any other reports of this behavior. Alternatively, I wonder if #1541 may be the culprit here. Please advise. 

Barring any further comments here, we'll likely mark this issue as closed at our next issue triage, in ~2 weeks. 

#monitoringlove

**Comment by blakebarnett** [comment]
Thanks for the update, I think what was happening is our instances on AWS weren't getting time to shutdown properly.  We've since started using the the ASG lifecycle-events SNS topic to do this automatically.
