### ISSUE TITLE
Sensu Windows Client leaves orphaned Ruby process sometimes

### ISSUE THREAD

**Issue by tmmukunn** [sensu/sensu#1440]
We upgraded our Sensu windows client from 0.14.0 to 0.25.3.1 and noticed the following problem:

Sometimes when I have the Sensu client service stopped, the sensu client process hangs around for a while until eventually it does die, but leaves behind a ruby process.  This is also problematic if sensu client is started or restarted, because it appears the orphaned ruby process and the current ruby process are doing the same thing, except the orphaned one generates the WerFault process.  Leaving a server unmonitored and because of things we need to do where we restart the sensu client has left us with multiple orphaned ruby processes running.  This also tends to put a CPU strain on the sensu server when this happens and we didn't realize 80 some orphaned processes were running.

Looking at the sensu-client.wrapper.log file, i see the following:
2016-09-09 12:35:15 - Stopping Sensu-client
2016-09-09 12:35:15 - ProcessKill 3976
2016-09-09 12:35:15 - Send SIGINT 3976
2016-09-09 12:35:15 - SIGINT to 3976 failed - killing as fallback
2016-09-09 12:35:15 - Stop exceptionMessage:Process with an Id of 2576 is not running.Stacktrace:  at System.Diagnostics.Process.GetProcessByProcessId(Int32 processId)
at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
at winsw.WrapperService.StopProcessAndChildren(Int32 pid)
at winsw.WrapperService.StopIt()
at winsw.WrapperService.OnStop()

3976 was the Ruby process
2576 was cmd.exe running under the Ruby process.  That process exited with a status of 0 at 12:35:15.682.  I'm guessing the cmd.exe exited before the fallback had a chance to kill it
I did see a conhost.exe that was a child process of Ruby that had an exit status of -1 at 12:35:15.8082237
Sensu-client.exe had a process exit at 12:35:45.919.

**Comment by mhzgh** [comment]
Seems exactly like the problem i have.

I Have a fair number of windows machines (around 30) from 2003 to 2012R2 with client versions v0.19 to v0.26

The crashed instances are still connected to rabbitmq. 
So, on the rabbitmq server,  a "rabbitmqctl list_connections | awk '{ print $2 }' | sort | uniq -d" lists several ip-addresses from client machines, which imo SHOULD only run 1 instance.
This happens several times a week since around versions 0.2x i would guess.
Already improved my daily logrotate service-restart script to kill those stale processes.

But I also did not found the real cause yet. 

Not sure if that problem MAY also occur on linux and just dont shows up, because logrotation is not a concern there - and therefor no frequent scheduled restarts are required.
Can not think of an occurrence I had with this in linux for the past year.

**Comment by mhzgh** [comment]
Another thing I also want to share is that the left processes still have a handle on the logfile.
See the example below, where several handles from multiple PIDs are active. (in normal operation you only have 1 pid here)

ruby.exe           pid: 10340  type: File           284: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 10340  type: File           28C: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 11468  type: File           28C: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 11468  type: File           294: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 3840   type: File           290: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 3840   type: File           298: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 10384  type: File           28C: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 10384  type: File           294: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 5056   type: File           288: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 5056   type: File           290: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 3756   type: File           28C: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 3756   type: File           294: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 8892   type: File           28C: C:\var\log\sensu\sensu-client.log
ruby.exe           pid: 8892   type: File           294: C:\var\log\sensu\sensu-client.log

**Comment by cabecada** [comment]
https://github.com/sensu/sensu/issues/1480 i have had similar issues

**Comment by dalesit** [comment]
We also see this problem - when doing a service restart, it stops the service but leaves a ruby process running. Consequently, when puppet does a config change and notifies the sensu-service, you get a second process running, which leaves to flapping behaviour with multiple results - one OK, one unknown eg:

history
0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0

These have all been running on 0.23.3

Going to update to 0.26.3 to get the new silence behaviour, but from the sound of it, this bug will continue.

Manually killing the process seems to take multiple attempts (or it is just really slow). Looking to put together a powershell script to force quit the processes and then restart.

**Comment by iforapsy** [comment]
I've tracked the problem to winsw, Sensu's service wrapper. When one stops the Sensu service, winsw tries to terminate all of Sensu's child processes before terminating Sensu. However, there is a race condition if winsw finds a child process of Sensu, but the child process dies of its own accord before winsw terminates it. Winsw does not correctly catch the exception from this scenario so it stops terminating any more processes. This leaves the Ruby interpreter running Sensu alive. As Sensu is constantly spawning short-lived child processes for plugins, this issue is quite prevalent.

I made [a pull request with a fix](https://github.com/kohsuke/winsw/pull/166). You will want to build WinSW.NET4.exe and use that to replace sensu-client.exe.

**Comment by oleg-nenashev** [comment]
I have integrated the change into WinSW.
You can get a SNAPSHOT release of this version here: https://github.com/kohsuke/winsw/releases/tag/untagged-0ef3724da6f50f39f099

**Comment by oleg-nenashev** [comment]
Fixed the link above (just to point to the pre-release instead of the draft)

**Comment by cwjohnston** [comment]
Thanks @iforapsy and @oleg-nenashev, this looks promising. We will work on integrating this into a Windows build for testing.

**Comment by oleg-nenashev** [comment]
@cwjohnston great. I'm finalizing the WinSW2 release now, so I will appreciate any feedback.
You may also want to enable [Runaway Process Killer](https://github.com/kohsuke/winsw/blob/master/doc/extensions/runawayProcessKiller.md) if such orphaned processes happen due to another reason.

**Comment by mhzgh** [comment]
Great news, thanks for your efforts. :)
Will try and report back!

**Comment by oleg-nenashev** [comment]
@mhzgh Just take the recent 2.0.2 then. There are more fixes around process management

**Comment by dzeleski** [comment]
Running into the same issue here as well. History on powershell checks looks like this:
```
0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0, 3221225794, 0
```

**Comment by cwjohnston** [comment]
@tmmukunn @mhzgh @dzeleski is this problem ongoing for you? We started shipping Sensu with  WinSw 2.x circa version 0.27.

**Comment by dzeleski** [comment]
That's a great question. I'm out of the office until Monday morning. But I have not noticed any issues recently. I'll double check and get back to you as soon as I can.



On Aug 4, 2017, at 4:49 PM, Cameron Johnston <notifications@github.com<mailto:notifications@github.com>> wrote:


@tmmukunn<https://github.com/tmmukunn> @mhzgh<https://github.com/mhzgh> @dzeleski<https://github.com/dzeleski> is this problem ongoing for you? We started shipping Sensu with WinSw 2.x circa version 0.27.

**Comment by mhzgh** [comment]
Wow quite a delay on my side... ;( sorry. Haven't had the time to focus on some monitoring topics during the last months...
Majority of the environment was updated from 0.26 to sensu 1.0.2 the last 2 weeks ago. Havent had any issues with windows-service since that. 

But i think the results are not really comparable anymore, at least in my case:
I configured the sensu-client.xml to run without the "-l" switch (lowercase L, for logging to stdout)
I am aiming for winsw to take over logging, with the "logpath" and "log mode" directives to take over.
I gladly recognized, that this allows logfile-rotation w/o my selfwritten service-restart script now. Great work, thanks! I already tested this and it seems to work quite fine.

However, I decided to leave logging disabled for the default sensu-windows-client in my CHEF setup (commented out "logpath" directive) and use it manually for a temporary time-frame, where required.

**Comment by mhzgh** [comment]
If you want, i could re-configure my old setup in some chosen machines. So this would use the "-l" directive and issue a logfile rotation via sensu-client restart once a day. Let me know if that would be helpful.

**Comment by dzeleski** [comment]
@cwjohnston We dont see this occurring currently on 0.27+

**Comment by cwjohnston** [comment]
Closing as we believe the winsw run-away process killer is effective in addressing abandoned processes.
