### ISSUE TITLE
Sensu should use Semantic Versioning (http://semver.org/)

### ISSUE THREAD

**Issue by spang** [sensu/sensu#1448]
## Expected Behavior

Sensu only makes incompatible changes in major versions.
## Current Behavior

Sensu makes incompatible changes in minor versions, e.g. 0.26.
## Possible Solution

Switch to semantic versioning, described on http://semver.org/.
## Context

Our off-hours "subdue" attribute on handlers unexpectedly stopped working after an upgrade from 0.25 to 0.26, resulting in an engineer being paged early in the morning for a non-critical issue.

**Comment by cabecada** [comment]
From semver doc


  1.  Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

Jokes apart, I guess we have to look at changelog before we upgrade, have a test suite ready to expect any issues from an upgrade :).

I have been told this many times, so just sharing my experience:)


Thanks,

Vijay


Thanks
Vijay

Sent from my iPhone

On 17-Sep-2016, at 1:49 AM, Christine Spang <notifications@github.com<mailto:notifications@github.com>> wrote:

Expected Behavior

Sensu only makes incompatible changes in major versions.

Current Behavior

Sensu makes incompatible changes in minor versions, e.g. 0.26.

Possible Solution

Switch to semantic versioning, described on http://semver.org/.

Context

Our off-hours "subdue" attribute on handlers unexpectedly stopped working after an upgrade from 0.25 to 0.26, resulting in an engineer being paged early in the morning for a non-critical issue.

-

**Comment by spang** [comment]
That's a good point that since Sensu is still on major version 0, it technically falls under the "everything can change" note of semver. However, as a project that's been around for 5 years and is (as far as I can tell) intended to be use as the backbone of production alerting systems, perhaps it's time to go 1.0!

**Comment by cwjohnston** [comment]
Hi @spang, thanks for opening this issue, I think you've raised an important point. We are overdue in about our plans for releasing Sensu 1.0 and there have been a number of backward incompatible changes introduced in recent versions. 

Although it's not explicitly documented in the project, we do believe we're adhering to semver here, just as we endeavour to do with supporting libraries like sensu-redis, sensu-transport, etc. We intend to continue that with Sensu Core itself as it reaches that 1.0 major version release. I'm happy to open a PR amend the project readme indicating that we follow semver.

We do our level best to provide concrete warnings around breaking changes via the changelog, both here in github and [on our website](https://sensuapp.org/docs/latest/overview/changelog.html). Suggestions on how we can improve this communication are welcome!

I think I speak for everyone on Team Sensu when I say we really want to release 1.0, but we also know we have work left to do. Of course that means more change is coming, so you may want to take a look at the milestones on this project for some idea of the changes we are planning for upcoming versions.

**Comment by julian7** [comment]
@cwjohnston Is the road to 1.0 public? I've looked at milestones, but it's up to 0.28. Let me tell you I can't wait for 0.28 :)

**Comment by calebhailey** [comment]
@julian7 at this time we are thinking that 0.28 will be the 1.0 release candidate. You should see us commit to a 1.0 milestone in the repo in the coming weeks, and then the countdown shall begin! :)

**Comment by portertech** [comment]
Sensu the upcoming 0.29 is officially the 1.0 release candidate - https://github.com/sensu/sensu/pull/1629

Like the Sensu Core libs, e.g. sensu-setttings, Sensu will use SEMVER post 1.0.

**Comment by mbbroberg** [comment]
@spang thanks you making this suggestion! The maintainers are super pumped to be able to commit to SemVer going forward. 

Keep the feedback coming and ping me if you ever want to talk Community: matt@ `sensu.io`.

**Comment by majormoses** [comment]
Yay! this has been bugging me for a while, I have been using sensu for about 4 years in production as my primary monitoring solution and I definitely feel that we need of stop pretending like it's ok to make breaking changes without a major release. 1.0 here we come!
