### ISSUE TITLE
Stop storing passwords in plain text in config files

### ISSUE THREAD

**Issue by Northwood128** [sensu/sensu#1489]
Hi everyone! 

First of all, I love Sensu. Its an awesome tools and I'm running it to monitor our stuff at work. 

Now, to the real issue. How do I explain to our SOC that passwords are stored in plain text on the configuration files? 

I know that passwords can be redacted on check client configuration so it doesn't get logged. But, lets say someone breaks into a server, or some gains access to a developer computer and access any host with the sensu client installed and checks the client configuration? 

I would like to have an option to store passwords in a secure way so our SOC team can sleep at nigth :)

Thanks!!

**Comment by kronkite115** [comment]
Don't put the passwords on hosts you don't trust and don't reuse passwords.  Regardless of how the password is stored it will still be recoverable to an attacker.  This is true for anything that stores passwords.
The best thing you can do it lock down the configuration files so they are only readable by the sensu user.  Also, make certain you are not sending passwords over the transport, passwords should only exist on the clients that are doing the check.

**Comment by virtualdxs** [comment]
Yeah, unfortunately @kronkite115 is right. If the password is available to the system at check runtime, it's available to an attacker with system privileges at check runtime. My only suggestions as for a way to ameliorate this are 1. Setting up the system being checked so that the necessary information can be accessed without auth, or 2. Creating an account that only provides the necessary information for the check and having Sensu use that so if an attacker gets in the attack surface is reduced and when you discover the breach you can easily revoke that account's access without side effects.

**Comment by Northwood128** [comment]
Thanks for the suggestions guys!! I'll use these arguments when they approach me. Cheers!
