### ISSUE TITLE
Debian glibc 2.12 dependency problem

### ISSUE THREAD

**Issue by kosli** [sensu/sensu#1494]
I have a few machines that still are using debian squeeze (sic!) and i am running sensu-clients on them. 

Until version 0.23.2-1 of the debian package everything worked fine, but from version 0.23.2-2 on, the client cannot start because of glibc dependency problems: 

Starting sensu-client:/opt/sensu/embedded/bin/ruby: /lib/libpthread.so.0: version `GLIBC_2.12' not found (required by /opt/sensu/embedded/lib/libruby.so.2.3)
 failed!

Was this on purpose? Was the ruby version changed in between the two builds (and all the following)? 

How are the debian packages build? I assume by this dockerfile here: https://github.com/sensu/sensu-build/blob/master/dockerfiles/debian-i386 ? So i could see if i can build my own packages...

**Comment by amdprophet** [comment]
Hi @kosli,

This happened as a result of moving from full-blown VMs to Dockerfiles in our build pipeline. As Debian Squeeze was EOL'd in February 2016 we do not plan to address the issue you have raised.

The dockerfile you have linked to is the container used for Debian i386 builds. As a note, Sensu 0.27 and forward will be built using https://github.com/sensu/sensu-omnibus instead of sensu-build.

We plan to release a list of supported platforms in the near future.

#monitoringlove
