### ISSUE TITLE
[Feature] - Registration timestamp in Client registry

### ISSUE THREAD

**Issue by mcbsdEU** [sensu/sensu#1619]
## Expected Behavior
Client registry to contain registration timestamp

## Current Behavior
Client registry contains general timestamp which is something like "last update" triggered by keepalive every 20s.

## Possible Solution
Registration handler could be used to trigger manual check publishment of checks which other checks rely on.

However, this is just last resort option...

## Steps to Reproduce (for bugs)
N/A

## Context
I came to this idea by having an issue with checks which must be postponed due to just recent client registration.
It takes some time till all checks for given client are executed for the first time (etc. performance data population to Graphite...) and client become consolidated.

The are certain checks which rely on other checks.
When having registration timestamp in client registry, check could be configured to proceed only when client has been registered at least for 5 minutes.

This would solve/reduce false alarm storm when client is registered for the first time and all checks are scheduled right away and it takes a while till client becomes consolidated and all involved 3rd party databases/tools has data populated for given client.

Maybe this idea could be done in different way, but still, registration timestamp is valuable information.
..............
Proxy clients should have that feature as well.
Registration timestamp must be permanent during existence.
POST request to /clients endpoint  should not alter registration timestamp when using API for client data update.
Sure, _first_ usage of this POST request (etc. to populate proxy client) must "register" registration timestamp.
..............

## Your Environment
* Sensu version used: 0.28.4
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7
* Transport and runtime versions (e.g. RabbitMQ 3.6.2 on Erlang 18.2): RabbitMQ

Thanks

**Comment by mcbsdEU** [comment]
Ok, mentioned use-case is not proper one as every check turns into API call and env. with lot of checks....meh.
Registration handler seems to be not as last option as it seemd.
Anyway, taking away mentioned use-case, as I wrote, registration timestamp is valuable and may find usage in other areas.

**Comment by mcbsdEU** [comment]
Hi, just reminder on this one:) Just would like to know at least opinion from Sensu devs or other Sensu users.
Thanks!

**Comment by mbbroberg** [comment]
👋 hey @mcbsdEU thanks for staying on top of this! 

As you know, the core team has shifted the focus toward [sensu-go (aka 2.0)](https://github.com/sensu/sensu-go/). I mention that not because that means we will stop supporting the current project, but because new features are prioritized there. 

As thoughtful as your request is, the team focusing on Sensu write it until we have **a lot** more interest from others to increase its urgency. If this is important to you, please reach out to further Sensu users [in Slack](http://slack.sensu.io) and on [our mailing list](https://groups.google.com/forum/#!topic/sensu-users) to get more momentum. Then, and only then to be honest, will we consider moving forward. 

So much love for your effort here and please hit me up for feedback here or `@matt` on Slack 👌

**Comment by mcbsdEU** [comment]
Hi,

thanks for feedback. This feature is not critical, it's more _very_ nice to have:) Anyway, I'll try to ping users on Slack.
Thanks a lot.
