### ISSUE TITLE
sensu osx - broken link from the doc 0.28

### ISSUE THREAD

**Issue by patrickatomic** [sensu/sensu#1624]
The doc here: https://sensuapp.org/docs/latest/platforms/sensu-on-mac-os-x.html
indicates sensu 0.28-1-1 for OSX available... but the link is broken....
curl -LO https://sensu.global.ssl.fastly.net/osx/sensu-0.28.1-1.pkg

and when browsing to https://sensu.global.ssl.fastly.net/osx/,
0.27 seems to be the latest... 0.28 doesn't show up there....

**Comment by cwjohnston** [comment]
Hi @patrickatomic, thanks for bringing this to our attention. We've just published up-to-date 0.28.4-1 builds for macOS on our [downloads page](https://sensuapp.org/downloads).

To directly address the broken link on the macOS page, I believe we should remove the URLs for particular packages from these platform-specific pages. We're tracking that issue here: https://github.com/sensu/sensu-docs/issues/532
