### ISSUE TITLE
event handlers fire for silenced checks with a configured source

### ISSUE THREAD

**Issue by robertlabrie** [sensu/sensu#1655]
It looks like silenced isn't being honored when a check is defined with a source.

## Expected Behavior
Silenced checks don't fire the event handler when silenced.

## Current Behavior
Silenced checks do fire the event handler.

## Steps to Reproduce (for bugs)
1. Define a check
2. Silence it
3. let the check run
4. get paged because the event handler fired

## Context
Gettin paged on PD for silenced checks

## Your Environment
Uchiwa 0.22.1-1
Sensu 0.28.0-1.el6

Sorry I had to obfuscate some IPs and hostnames, the check name, else it's unchanged.
Check definition:
`{
  "checks": {
    "vpn_eu_check_secondary": {
      "command": "check-aws-vpc-vpn.rb --use-iam --aws-region eu-west-1 --vpn-connection-id XXXXXXXX --only-critical",
      "subscribers": [
        "central_checks_eu"
      ],
      "handlers": [
        "pagerduty",
        "default"
      ],
      "refresh": 1800,
      "interval": 150,
      "source": "amazon",
      "occurrences": 2,
      "description": "monitor the IPSEC vpn connections between corp and AWS EU",
      "playbook": "https://confluence.intranet.local/browse/OPS-3977"
    }
  }
}`

It's silenced:
`  {
    "id": "client:amazon:vpn_eu_check_secondary",
    "subscription": "client:amazon",
    "check": "vpn_eu_check_secondary",
    "reason": "VPN connection between corp and EU is not a pressing issue as it's not in use. Stashing without expiration. (andrthen)",
    "creator": null,
    "expire_on_resolve": false,
    "timestamp": 1491835445,
    "expire": -1
  }`

From the logs:
`{
	"timestamp": "2017-04-10T18:26:41.700181+0000",
	"level": "info",
	"message": "processing event",
	"event": {
		"client": {
			"name": "amazon",
			"address": "unknown",
			"subscriptions": [],
			"keepalives": false,
			"version": "0.25.5"
		},
		"check": {
			"command": "check-aws-vpc-vpn.rb --use-iam --aws-region eu-west-1 --vpn-connection-id XXXXXXXX --only-critical",
			"subscribers": ["central_checks_eu"],
			"handlers": ["pagerduty", "default"],
			"refresh": 1800,
			"interval": 150,
			"source": "amazon",
			"occurrences": 2,
			"description": "monitor the IPSEC vpn connections between corp and AWS EU",
			"playbook": "https://confluence.intranet.local/browse/OPS-3977",
			"name": "vpn_eu_check_secondary",
			"issued": 1491848800,
			"executed": 1491848800,
			"duration": 1.203,
			"output": "CheckAwsVpcVpnConnections CRITICAL: 'vpn-eu-secondary' shows both tunnels as DOWN - [ X.X.X.X => IPSEC IS UP | X.X.X.X => IPSEC IS DOWN ]\n",
			"status": 2,
			"type": "standard",
			"origin": "checks_eu.dub.example.com",
			"history": ["2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "0", "2", "2"],
			"total_state_change": 11
		},
		"occurrences": 2,
		"occurrences_watermark": 2,
		"action": "create",
		"timestamp": 1491848801,
		"id": "974e242c-eaa4-4136-be25-49c8c230754d",
		"last_state_change": 1491848651,
		"last_ok": 1491848651,
		"silenced": false,
		"silenced_by": []
	}
}`

**Comment by cabecada** [comment]
your client subscriptions are empty?
https://github.com/sensu/sensu/blob/master/lib/sensu/server/process.rb#L467
handler will respect silencing when subscriptions are set.


On Apr 11, 2017, at 6:17 PM, robertlabrie <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like silenced isn't being honored when a check is defined with a source.

Expected Behavior

Silenced checks don't fire the event handler when silenced.

Current Behavior

Silenced checks do fire the event handler.

Steps to Reproduce (for bugs)

  1.  Define a check
  2.  Silence it
  3.  let the check run
  4.  get paged because the event handler fired

Context

Gettin paged on PD for silenced checks

Your Environment

Uchiwa 0.22.1-1
Sensu 0.28.0-1.el6

Sorry I had to obfuscate some IPs and hostnames, the check name, else it's unchanged.
Check definition:
{ "checks": { "vpn_eu_check_secondary": { "command": "check-aws-vpc-vpn.rb --use-iam --aws-region eu-west-1 --vpn-connection-id XXXXXXXX --only-critical", "subscribers": [ "central_checks_eu" ], "handlers": [ "pagerduty", "default" ], "refresh": 1800, "interval": 150, "source": "amazon", "occurrences": 2, "description": "monitor the IPSEC vpn connections between corp and AWS EU", "playbook": "https://confluence.intranet.local/browse/OPS-3977" } } }

It's silenced:
{ "id": "client:amazon:vpn_eu_check_secondary", "subscription": "client:amazon", "check": "vpn_eu_check_secondary", "reason": "VPN connection between corp and EU is not a pressing issue as it's not in use. Stashing without expiration. (andrthen)", "creator": null, "expire_on_resolve": false, "timestamp": 1491835445, "expire": -1 }

From the logs:
{ "timestamp": "2017-04-10T18:26:41.700181+0000", "level": "info", "message": "processing event", "event": { "client": { "name": "amazon", "address": "unknown", "subscriptions": [], "keepalives": false, "version": "0.25.5" }, "check": { "command": "check-aws-vpc-vpn.rb --use-iam --aws-region eu-west-1 --vpn-connection-id XXXXXXXX --only-critical", "subscribers": ["central_checks_eu"], "handlers": ["pagerduty", "default"], "refresh": 1800, "interval": 150, "source": "amazon", "occurrences": 2, "description": "monitor the IPSEC vpn connections between corp and AWS EU", "playbook": "https://confluence.intranet.local/browse/OPS-3977", "name": "vpn_eu_check_secondary", "issued": 1491848800, "executed": 1491848800, "duration": 1.203, "output": "CheckAwsVpcVpnConnections CRITICAL: 'vpn-eu-secondary' shows both tunnels as DOWN - [ X.X.X.X => IPSEC IS UP | X.X.X.X => IPSEC IS DOWN ]\n", "status": 2, "type": "standard", "origin": "checks_eu.dub.example.com", "history": ["2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "2", "0", "2", "2"], "total_state_change": 11 }, "occurrences": 2, "occurrences_watermark": 2, "action": "create", "timestamp": 1491848801, "id": "974e242c-eaa4-4136-be25-49c8c230754d", "last_state_change": 1491848651, "last_ok": 1491848651, "silenced": false, "silenced_by": [] } }

**Comment by robertlabrie** [comment]
Hi,
Thanks for your reply, but I'm not sure what you mean though. The check definition has `"subscribers": [ "central_checks_eu" ]`

**Comment by robertlabrie** [comment]
client.json on the host running the check:
`{
  "client": {
    "address": "10.222.0.72",
    "subscriptions": [
      "central_checks_eu",
      "base"
    ],
    "name": "checks_eu.dub.example.com",
    "keepalive": {
      "playbook": "https://confluence.intranet.local/browse/OPS-3848",
      "thresholds": {
        "warning": 120,
        "critical": 180
      },
      "handlers": [
        "default",
        "pagerduty"
      ],
      "refresh": 1800
    },
    "deregister": true,
    "deregistration": {
      "handler": "deregister_client"
    },
    "elastic_search": {
      "monitoring": {
        "username": "monitoring",
        "password": "XXXXXXXXXXXXXXXXXXXXXXXXX"
      }
    },
    "load": {
      "shortterm": {
        "warning": 3,
        "critical": 4
      }
    }
  }
}`

**Comment by cwjohnston** [comment]
@robertlabrie I believe @cabecada is referring to the `amazon` proxy client, which is showing an empty set of subscriptions. This is the reason that your silencing entry has failed to match the event in question.

Proxy clients are automatically created when defined as the `source` of a check result or when created via the `/clients` API endpoint. It sounds like your `amazon` client was created by the former case in a version of Sensu prior to 0.26.2. 

You can delete the `amazon` client via the Sensu API or Dashboard, and it should be recreated with the required subscription the next time your Sensu server processes a check result specifying `amazon` as the value of the `source` attribute. Alternately, you can update the `amazon` client's subscriptions by [POSTing JSON to the `/clients` API endpoint](https://sensuapp.org/docs/latest/api/clients-api.html#clients-post).

**Comment by robertlabrie** [comment]
@cwjohnston interesting .. should I upgrade the client on the machine which is running the check to >= 0.26.2 (it's presently 0.25.something)? Or is that logic handled purely in the API and deleting it will sort things out

**Comment by cwjohnston** [comment]
@robertlabrie the client registry entry for the `amazon` proxy client, stored in Redis, is what's at issue here. This client registry entry is created and updated by the sensu-server or sensu-api process, depending on the scenario. Upgrading the sensu-client won't have any effect on the `amazon` client's registry entry.
