### ISSUE TITLE
No init scripts in /etc/init.d on Ubuntu 16.04 (xenial)

### ISSUE THREAD

**Issue by nagyt234** [sensu/sensu#1664]
## Expected Behavior
After installing the sensu package the init scripts for sensu-server, sensu-client and sensu-api should be be in /etc/init.d, to allow to start the services at system boot after using `update-rc.d sensu-... defaults`.
## Current Behavior
I get the following:
```
$ update-rc.d sensu-server defaults
update-rc.d: error: initscript does not exist: /etc/init.d/sensu-server
```
## Steps to Reproduce (for bugs)
```
wget -q https://sensu.global.ssl.fastly.net/apt/pubkey.gpg -O- | sudo apt-key add -
export CODENAME=xenial
echo "deb     https://sensu.global.ssl.fastly.net/apt $CODENAME main" | sudo tee /etc/apt/sources.list.d/sensu.list
sudo apt-get update
sudo apt-get install sensu
update-rc.d sensu-server defaults
```
## My Environment
* Sensu version used: 0.29.0-7
* Operating System and version: Ubuntu 14.04

**Comment by Evesy** [comment]
Hi,

Since 0.27 Sensu now provides unit files rather than sysv init scripts where systemd is default: https://sensuapp.org/docs/0.27/overview/changelog.html#core-v0-27-0-important

I believe Ubuntu 16.04 uses systemd as its default init, so you should find the relevant unit files are there and can be used :)

**Comment by portertech** [comment]
@Evesy thank you for helping :+1:

**Comment by nikgibbens** [comment]
I am unable to locate the systemd unit files for Sensu. Any idea where they are located?
