### ISSUE TITLE
yum not finding signing key

### ISSUE THREAD

**Issue by ssirobertreilly** [sensu/sensu#1697]
rhel 7 used ansible to add the repo package install failed so I ran it manually and below is the output.
cheers,
rr
```=====================================================================================================
 Package             Arch                 Version                          Repository           Size
=====================================================================================================
Installing:
 sensu               x86_64               1:0.29.0-11.el7                  sensu                28 M

Transaction Summary
=====================================================================================================
Install  1 Package

Total size: 28 M
Installed size: 81 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/sensu/packages/sensu-0.29.0-11.el7.x86_64.rpm:
 Header V4 RSA/SHA1 Signature, key ID 8c2d8ffa: NOKEY


Public key for sensu-0.29.0-11.el7.x86_64.rpm is not installed

**Comment by ssirobertreilly** [comment]
i see we can just skip the key checking but would be nice to have validation the file has not been compromised.

**Comment by cwjohnston** [comment]
@ssirobertreilly pub key is available at https://repositories.sensuapp.org/yum/pubkey.gpg

**Comment by majormoses** [comment]
@cwjohnston any reason this is not done by the ansible playbook? I know the chef cookbooks do but I know not nearly enough about ansible to know if there is some reason this is not done.

**Comment by cwjohnston** [comment]
@majormoses If this isn't implemented in the Ansible playbook, I assume its because we haven't made it clear how to use it.

RPM signing was only recently implemented as part of our build process, and we haven't done much to communicate the details about where to retrieve or how to use the public key. I'm not fully versed in how public keys are typically distributed but I'm under the impression that some vendors package the key itself for installation prior to the signed package. 

Relatedly, we are not currently signing uchiwa packages, which are part of the same repository, so we can't advocate folks configuring `gpgcheck=1` in the yum repo configuration without side-effects.

**Comment by majormoses** [comment]
I see, is there an issue that we should track this on? Once you have everything signed to me there are 2 approaches and they are not mutually exclusive, you can say pull this key from this location over https here or you can overwrite the location in the "wrapper" playbook to allow it to be hosted on an internal trusted source if you are worried about someone MITM.

The chef equivalent I have done before for a different monitoring product: 
- https://github.com/Netuitive/chef-netuitive/blob/80b43a841d94c56e0782b904ef53ed085bf446a1/libraries/provider_repo.rb#L60-L66
- https://github.com/Netuitive/chef-netuitive/blob/80b43a841d94c56e0782b904ef53ed085bf446a1/attributes/default.rb#L16
