### ISSUE TITLE
Unexpected behavior client.json

### ISSUE THREAD

**Issue by guannais** [sensu/sensu#1709]
## Unexpected client Behavior
Add many clients in sensu server.

## Current Behavior

1. If I have 2 different json file with client section sensu server it´s mergering configuration. 
2. If I have 2 different clients sections at the same client.json file sensu-server is only using the last one.

## Steps to Reproduce (for bugs)
The first case (2 different json file with one client section in each file)
client.json file
`{
   "client":{
      "name":"SENSUSERVER",
      "address":"localhost",
      "deregister":true,
      "deregistration":{
         "handler":"deregister_client"
      },
      "subscriptions":[
         "Linux",
         "SW: Redis",
         "SW: RabbitMQ"
      ]
   }
}`
temp.json file
`{
   "client":{
      "name":"switch-x",
      "address":"unknown",
      "subscriptions":[
      ],
      "keepalives":false
   }
}`

This is the API result (SENSUCLI is another machine)
`curl -s -u *****:***** http://localhost:4567/clients | jq .
[
  {
    "name": "switch-x",
    "address": "unknown",
    "deregister": true,
    "deregistration": {
      "handler": "deregister_client"
    },
    "subscriptions": [
      "Linux",
      "SW: Redis",
      "SW: RabbitMQ",
      "client:switch-x"
    ],
    "keepalives": false,
    "version": "1.0.0",
    "timestamp": 1500825797
  },
  {
    "name": "SENSUCLI",
    "address": "localhost",
    "keepalives": false,
    "deregister": true,
    "deregistration": {
      "handler": "deregister_client"
    },
    "subscriptions": [
      "Linux",
      "client:SENSUCLI"
    ],
    "version": "1.0.0",
    "timestamp": 1500825805
  }
]`

When I ask API to return current clients it´s mergering both clients options.

The second case (2 different clients sections at the same client.json)
I have one client.json file

`    {
       "client":{
          "name":"SENSUSERVER",
          "address":"localhost",
          "deregister":true,
          "deregistration":{
             "handler":"deregister_client"
          },
          "subscriptions":[
             "Linux",
             "SW: Redis",
             "SW: RabbitMQ"
          ]
       },
       "client":{
          "name":"switch-x",
          "address":"unknown",
          "subscriptions":[
          ],
      "keepalives":false
       }
    }`

This is the API result (SENSUCLI is another machine)
`curl -s -u *****:***** http://localhost:4567/clients | jq .
[
      {
        "name": "switch-x",
        "address": "unknown",
        "subscriptions": [
          "client:switch-x"
        ],
        "keepalives": false,
        "version": "1.0.0",
        "timestamp": 1500825090
      },
      {
        "name": "SENSUCLI",
        "address": "localhost",
        "keepalives": false,
        "deregister": true,
        "deregistration": {
          "handler": "deregister_client"
        },
        "subscriptions": [
          "Linux",
          "client:SENSUCLI"
        ],
        "version": "1.0.0",
        "timestamp": 1500825085
      }
    ]
`

When I ask API to return current clients it only shows me the last one.

* Sensu version used: 1.0.0
* Operating System and version (Ubuntu 16.04):
* Transport and runtime versions (RabbitMQ 3.6.2 on Erlang 18.2):

**Comment by flowerysong** [comment]
This is expected behaviour.

With two files you have two different JSON objects that can be individually parsed and then merged, while the second case is a single JSON object with duplicate keys. Duplicate keys are technically allowed by the JSON spec, but the most common parser behaviour is to keep one of the values and throw away the duplicate(s).

**Comment by portertech** [comment]
@guannais you can only have one Sensu client definition per machine (for sensu-client), there is no client definition for the Sensu server (sensu-server). Sensu clients register themselves, you do not need to configure them centrally - https://sensuapp.org/docs/1.0/overview/architecture.html#monitoring-agent

Thanks @flowerysong, this is indeed the expected behaviour.

Setting JSON configuration snippets are deep merged, using this method: https://github.com/sensu/sensu-settings/blob/master/lib/sensu/settings/loader.rb#L387-L405. String and integer values are replaced, hashes are merged, and array are concatenated. You can optionally change the order of how JSON files are loaded and applied by naming them appropriately, alphabetically.
