### ISSUE TITLE
Feature Request: Take notes on checks without a silence

### ISSUE THREAD

**Issue by gwagner** [sensu/sensu#1715]
Today there are several hacky ways to take notes on a check. 
1. Apply JSON to a check on a server.  Uchiwa will puke the JSON out, not pretty but it works
1. Apply JSON to a client config.  Uchiwa will puke the JSON out, not pretty but it works
1. Silence a check and add notes (viewing this is disconnected in Uchiwa, but at least notes exist)

There is no way to add notes to a check or client through REST or Uchiwa and have that display in the UI or poll a client or check and get the notes back via REST.  Currently everything requires a deployment and a server restart to get new note type information into the system.

## Expected Behavior
A notes endpoint for checks and clients.  

I think a first step is notes, but this could lead to:

1. Linked notes by note ID
1. Auto expiring notes by date or by alarm clearing
1. A blame button with user lookup

## Current Behavior
Notes are cumbersome

## Possible Solution
/client/:client:/notes endpoint to accept notes
/results/:client/:check/notes endpoint to accept notes

**Comment by mcbsdEU** [comment]
This seems to be what I was looking for in more generic form.
I am interested into adding dynamic information into clients.
We use stashes for multiple purposes and I think that could be used also to store notes and use hostname as stash path etc.

The problem is, that there is no mechanism how to display content of stash into client information.
If that is supported, I think usage of stashes and this non-existing feature would solve many wishes of Sensu users.

For instance, client configuration could contain api filtering rule or exact path to stash
filter -> stashes?filter.content.hostname=superserver001
exact path -> superserver001/notes

Then, when requesting client info via API, internal mechanism would extract data from stash(es) and merge with "static" client data.

What do you think on that approach? (looking in direction of developers and users)

Thx

**Comment by portertech** [comment]
This would be a great Uchiwa feature request, to use Sensu API Stashes for check notes 👍 

@gwagner please create a Uchiwa feature request github issue at https://github.com/sensu/uchiwa Sensu Core does not need to implement anything to make this all possible.

I imagine Uchiwa can create and associated specific API Stashes with their corresponding Sensu client/check. /cc @palourde
