### ISSUE TITLE
Feature Request: Check Randomize Offset

### ISSUE THREAD

**Issue by gwagner** [sensu/sensu#1716]
Today we have our servers checking critical infra components for availability such as: Splunk / NTP / Artifact Storage / etc / etc.  Currently when checks are set to fire off, they will all fire at the same moment (within 2 seconds of each other).  I would like a config added to a check specification where a check (once received by the client) will randomize an offset of X seconds so i can spread a check that runs once every 10 minutes over a 10 minute period.

## Expected Behavior
Check is set with an interval of 10 minutes.  It would get a new config of randomized_offset of 600.  Every machine would get the check, randomize an offset from 0 to 600.  Check 1 would run at 0, check 2 would run at 35, check 3 would run at 274, check 3 would run at 122.  This would spread the load out more evenly rather than having services get bombarded by checks every 10 minutes for every machine.

## Current Behavior
Lots of machines hitting the same service without an offset MAKES THINGS MELT!!!!

## Possible Solution
Add a randomized_offset config that takes an integer.  When a machine receives the check, randomize an offset, wait that many seconds, then execute that check.

**Comment by cwjohnston** [comment]
@gwagner have you considered using a [roundrobin subscription](https://sensuapp.org/docs/latest/reference/clients.html#round-robin-client-subscriptions) running more frequently, i.e. shorter interval? This would ensure a check runs on only one host per execution request.

**Comment by gwagner** [comment]
@cwjohnston here is the scenario.  I am using sensu to run QA checks against metric data quality every 10 minutes for production metric data.  Currently with no offset, sensu server will schedule my checks to run every 10 minutes and the clients will suck up the checks and BLAST my api at roughly the same time.

By allowing a randomized offset, i can keep my 10 minute interval, but my checks will slowly hit the API over a 10 minute period instead of BLASTing the API all at the same time.

**Comment by mcbsdEU** [comment]
Just FYI,
something similar is already open, but from different perspective - and looking forward a lot for it!
#1650

**Comment by portertech** [comment]
Unfortunately, due to Sensu's pubsub design, the Sensu server is unable to splay regular check requests as it is unaware of how many Sensu clients subscribe to the subscriptions it is publishing to. We recently release Sensu 1.1.1, which includes splayed Proxy Check Request scheduling, as the Sensu server is fully aware of how many clients a check will be executed on, see [the documentation for more information (splay and splay_coverage)](https://sensuapp.org/docs/1.1/reference/checks.html#proxy-requests-attributes). This functionality closed #1650.

@cwjohnston's suggestion will solve this for some users and their use cases.
