### ISSUE TITLE
Feature request - Token substitution sets

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu#1793]
Currently, there seems to be no easy way of specifying multiple values to a check using token substitution. So far I have got around this by building a check template that accepts a comma-separated list of values and checking each one.

My suggestion would be to allow a dict or array in the check definition that is iterated over and supplies the check tokens.

For example:
```json
...
"check-service": {
  "command": "check-service.rb -name :::service::: -state :::state:::",
  "tokens": [
    {
      "service": "dns",
      "state": "running"
    },
    {
      "service": "dhcp",
      "state": "stopped"
    }
  ]
}
...
```

In the above example, each of the items in the array must supply tokens that will be used for substitution. This lets a single check definition check multiple things without needless separate checks. The issue with this example is that I'm not sure how to separate the output of each check.

---

Alternatively, `tokens` may need to be a dict, and each item would be under a unique key so that each check result is given a unique name automatically, for example:

```json
...
"check-service": {
  "command": "check-service.rb -name :::service::: -state :::state:::",
  "tokens": {
    "dns": {
      "service": "dns",
      "state": "running"
    },
    "dhcp": {
      "service": "dhcp",
      "state": "stopped"
    }
  }
}
...
```

And the check results would be generated under `check-service-dns` and `check-service-dhcp`. This would ideally not show each individual check within the API, only in the results (For sake of keeping the API & Uchiwa clean).

Any thoughts or suggestions?

**Comment by majormoses** [comment]
I feel like there is too much implementation logic here to translate cleanly. I think you can accomplish this fairly easy with defining the start and stopped services as two check definitions. Imagine something like this:
```json
"check-service-running": {
  "command": "check-service.rb -name :::services_running::: -state running",
}
```

```json
"check-service-stopped": {
  "command": "check-service.rb -name :::services_stopped::: -state stopped",
}
```

With some decent CM that should be really easy to accomplish. I might be totally missing important I am not seeing but this sounds like asking sensu to have some crazy data structure to support almost any combination of args together which seems very hard to account for misconfiguration.

**Comment by absolutejam** [comment]
Well, my biggest issue was the pollution to Uchiwa and the `checks` API. I started down this route before but ended up with over 20 different checks for different services, some of which only appear on a single server. I solved this somewhat by writing the `check-multi-template` stuff for Windows, but it just felt like a hack having to do this in the check plugin. I had the same remark from somebody in Slack, as they felt that having a single check with a command like the following:
```
  "command": "powershell.exe -file check-service-multi.ps1 -critical 'service1,service 2,service$3,...'"
```
was a bit unwieldy, and passes the issue off to the CM tool instead of getting Sensu to handle it, in what could be a more effective manner.

In my services example, I generally only need to check the service name, the `state` was just to illustrate multiple tokens. But another example might be having different warning values per disk, per client - Which isn't really possible with the current level of granularity.

**Comment by majormoses** [comment]
I guess what I am trying to say is that only your check script can know the relation of tokens to each other in these use cases. All sensu knows how to do is retrieve values and pass it to your check, if you need something like this you probably need to devise a more elaborate data structure in your check and have some string representation to pass on cli.

Some examples:
- `--service 'telnet:stopped, bind9:running, mybotnet:running'`
- `--disks 'disk1:crit,disk2:crit'`
- `--support-plan client1:pro,client2:enterprise`

If you need multiple args that relate to other other args that I think they should be separate checks to make it clear what the check is looking for. If you think this is wrong then you need to somehow pass a mapping of relations and the simplest solution is something like what I proposed above.

> was a bit unwieldy, and passes the issue off to the CM tool instead of getting Sensu to handle it, in what could be a more effective manner.

For who a person or machine? For a machine there is nothing wrong with a really long line and at the end of the day it will be passed like that to the cli anyways. I have a check for dynamodb tables that after rendering from CM (chef) the list of tables is over 1300 chars but I interact with my CM in a way that makes it easy to handle with essentially no effort. I generally solve that with something like this in my CM `"check-dynamodb-throttle.rb -r us-west-2 -t #{node['MY']['CUSTOM']['NAMESPACE']['DYNAMODB_TABLES'].join(',')} --warning-over 5 --critical-over 10"`. This seems far better to ask your CM to do something it is really good at doing than asking sensu to become CM.

I might be missing something so I will hit you up in slack and maybe a chat would best help me understand what the real issues and potential solutions are.

**Comment by majormoses** [comment]
So we talked about this over slack and one of the desires of this feature was to not just to do token substitution the goal was to on the fly create more instantiations of the check with the token substitution, building on the concept of a proxy check.

For example:
```
"check-service": {
  "command": "powershell check-service -name ::service:::",
  "service": "dhcp,dns"
}
```  

Would actually create 2 checks like this:
```
"check-service-dhcp": {
  "command": "powershell check-service -name dhcp"
}

"check-service-dns": {
  "command": "powershell check-service -name dns"
}
```

Aside from the fact that CM already makes doing that fairly trivial (to define the same check over and over again from say an array of values). In this case you are directly aware of the performance penalty being applied to invoke the check 50 times loading up any interpreter/vm, libraries, sdks, etc over and over. By moving that into sensu's problem to solve you are now hiding the fact that this is what is going to happen behind the scenes. While in some cases this might be OK there are others where it would bring your client to it's knees. 

Basically the end result is already solved by CM, it hides a lot of performance penalties that were not apparent even to advanced sensu users, and does not really bring anything new to the table. We could not find a valid use case where CM and/or rewriting the checks gave us the same or better experience.

To be clear even when using CM to accomplish this you may want/need to rewrite your checks to be multi resource aware because of the performance penalty of not is too high. Take for example the aws checks loading the `aws-sdk` is quite expensive about a year or so ago I had to add a bunch more instances of the sqs messages check. Doing so put that server (client) at 100% CPU all the time, even even after doubling and then quadrupling the number of CPU cores. After rewriting the check to accept multiple queues in a smaller number of instances of the check and removed the old ones the CPU utilization dropped to an average of 50-60% . 

We should make users life easier when it is the right thing to do, when the right thing to do is non trivial it means that we get to have these conversations to help solve the problem several layers down rather than one on the surface. Just my opinions, feel free to disagree.

**Comment by absolutejam** [comment]
Nothing else to add, you summed it up perfectly :smile: 

Thanks for taking the time to discuss it!
