### ISSUE TITLE
Feature request report interval

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu#1821]
It would be cool if you could specify a report interval for local sensu checks. A result should only be sent to the sensu server on state change or at the report interval.

In our case we run a lot of checks every minute at a lot of instances. A report interval features configured to 600 would be a 10x improvement.

In our snssqs use case we would also save a lot of money.

**Comment by mcbsdEU** [comment]
I am just thinking what is added value of report interval vs existing check interval...
If the checks run every 1 minute and you report every 10 minutes....why would you run those 9 dummy executes - they won't be used at all...
Maybe I am not getting full picture, but for me it seems that making check interval longer would have (almost) same effect.

**Comment by runningman84** [comment]
The benefit is that if something fails I know that in one minute. Otherwise I would notice this in 10 minutes.

So sensu client would need to store the last check result and last report time. If the current check result is different then the stored result or the last report time is older then the report interval it should send the result to the server.

**Comment by portertech** [comment]
Many of Sensu's internals and features rely on the consistent steam of check results regardless of indication state change. This proposed functionality would cause several issues, breaking existing functionality and behaviour. 

@runningman84 thank you for the feature request, but I am afraid due to the potential problems, I am going to close it.
