### ISSUE TITLE
Requesting keepalive status through API returns 404

### ISSUE THREAD

**Issue by sufiyanghori** [sensu/sensu#1902]
When trying to make a POST request to `http://<sensu-server>:4567/request` with the following payload,
```
{
  "check": "keepalive",
  "subscribers": [
    "Windows"
  ]
}
```

or 

`{"check":"keepalive","dc":"<DC name>","subscribers":["client:<client hostname>"]}`

We get `404` error.

But for all other checks it returns `202`,

```
{
  "check": "cpu-load-metrics",
  "subscribers": [
    "Windows"
  ]
}
```
This breaks the **issue request** button on keepalive check page on uchiwa as well,
(https://<sensu-server>/#/client/<DC>/<client>?check=keepalive)

Log from Uchiwa,

```
{"timestamp":"2018-09-11T09:04:21.943488333+10:00","level":"debug","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).postPayload","line":88},"message":"POST http://0.0.0.0:4567/request"}
{"timestamp":"2018-09-11T09:04:21.946197437+10:00","level":"warn","src":{"func":"github.com/sensu/uchiwa/uchiwa/sensu.(*Sensu).postPayload","line":93},"message":"POST http://0.0.0.0:4567/request returned: 404 Not Found"}
{"timestamp":"2018-09-11T09:04:21.946280171+10:00","level":"warn","src":{"func":"github.com/sensu/uchiwa/uchiwa.(*Uchiwa).IssueCheckExecution","line":44},"message":"404 Not Found"}

```

## Expected Behavior
Keepalive post request should be successful and return status should be `202 Accepted`

## Current Behavior

Return status is `404`

## Your Environment

* Sensu version used: 1.4.2
* Operating System and version : Centos7
* Transport and runtime versions ): RabbitMQ version 3.7.3

**Comment by cwjohnston** [comment]
HI @sufiyanghori, thanks for raising this issue. The keepalive check you're attempting to request is a special case in Sensu -- unlike standard or metric checks which are explicitly defined by configuration, this check is actually happening on the Sensu server. You can read more about this in our documentation here: https://docs.sensu.io/sensu-core/latest/reference/clients/#keepalive-events

Because keepalive check results are generated by the server on behalf of a client, the mechanism used by the `/request` API endpoint won't be able to find a check definition for a check named `keepalive`, hence the 404 return code. 

In light of the above and the pending general availability release of Sensu 2.0, we won't be making substantial changes to the way keepalive events are generated nor to the functionality of the `/request` API. 

I understand how this situation creates confusion for Sensu operators and I believe we shouldn't expose the option to issue a check request in the dashboard for `keepalive` when we know it will always receive a 404 from the API.

In the interest of improving the UX in the Uchiwa dashboard I have opened https://github.com/sensu/uchiwa/issues/797  project and will now close this issue.
