### ISSUE TITLE
Sesnu window client: "message":"[amqp] Detected TCP connection failure: unknown"

### ISSUE THREAD

**Issue by RetrofitAdmin** [sensu/sensu#1933]
Install sensu clinet on windows giving problem with Windows Client - Detected TCP Connection Failure.
sensu client on unix working fine. But windows is giving error. configuration files are below. Thanks in advance.

C:\opt\sensu>cat config.json
{
  "rabbitmq": {
    "host": "X.X.X.X",
    "vhost": "/sensu",
    "user": "sensu",
    "password": "sensu"
  }
}
C:\opt\sensu>cat conf.d/client.json
ï»¿{

  "client":  {
           "name": "windows-clinet",
           "address": "10.10.4.116",
           "subscriptions": ["retro_all"]
    }
  }
C:\opt\sensu>cat conf.d/redis.json
{
  "redis": {
    "password": "xxxxxxxx",
    "host": "10.10.1.212",
    "port": 6379
  }
}
C:\opt\sensu>cat conf.d/transport.json
{
            "transport": {
             "name": "rabbitmq",
             "reconnect_on_error": true
            }
           }

**Comment by cwjohnston** [comment]
Hi @RetrofitAdmin , sorry that the error message isn't very helpful here.  It's not clear which version of Sensu you are running on the Windows host, but historically there are 
a number of common causes for this message, including but not limited to:

* Incorrect RabbitMQ username/password
* Incorrect or inaccessible RabbitMQ host/port
* Host reset the connection because it was expecting TLS/SSL and client isn't configured for it

If you are still having trouble after examining these possibilities, please consider trying the [Sensu Community slack](https://slack.sensu.io) or our (Sensu Core Discourse)[https://discourse.sensu.io/c/Sensu-Core] for additional help.
