### ISSUE TITLE
Embedded ruby gems are not being used

### ISSUE THREAD

**Issue by jshort** [sensu/sensu#510]
I'm having problems getting the 4 main services to start due to errors like:

Starting sensu-server/opt/sensu/embedded/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find sensu (>= 0) amongst [bundler-1.3.4, minitest-1.6.0, rake-10.0.4, rake-0.8.7, rdoc-2.5.8, rubygems-bundler-1.1.1, rvm-1.11.3.6] (Gem::LoadError)
    from /opt/sensu/embedded/lib/ruby/1.9.1/rubygems/dependency.rb:256:in`to_spec'
    from /opt/sensu/embedded/lib/ruby/1.9.1/rubygems.rb:1210:in `gem'
    from /opt/sensu/bin/sensu-server:18:in`<main>'

I have checked the embedded ruby and this gem (and all of its dependencies are there).  The only way to get it to work is to locally install the sensu gem (and dependencies) and I'd prefer not to do this.

After getting server/api/client running, I ran into the same thing with sensu-dashboard.  I know that it's using the embedded ruby:

sensu    14562     1  0 15:54 ?        00:00:00 /opt/sensu/embedded/bin/ruby /opt/sensu/bin/sensu-server -b -c /etc/sensu/config.json -p /var/run/sensu/sensu-server.pid -l /var/log/sensu/sensu-server.log

However, it's not getting the embedded gems.

Thoughts/advice?

Thanks

**Comment by kali-brandwatch** [comment]
Just my 2 cents in case someone hits the same issue: If you are running checks that depend on sudo and your sensu install relies con ```EMBEDDED_RUBY=true``` you might run into problems if your setup has enabled ```secure_path``` setting in ```/etc/sudoers```

Since this sudoers setting does in fact force the sudo-ed script to run with a predefined ```$PATH``` disabling passing environment, and because the way sensu does use ```EMBEDDED_RUBY``` by prepending ```/opt/sensu/embedded/bin``` to the ```$PATH```, the side effect is that the ```EMBEDDED_RUBY``` setting will be apparently and silently ignored.

I banged my head against the wall for this issue until I found that the actual reason behind this is behaviour the way sudoers work, and the security feature of limiting ```$PATH``` for sudo-ed scripts.

As far as I can think, there is no good way to overcome this limitation (feature?) and you would need to force your sensu check ruby scripts to call ruby directly from ```#!/opt/sensu/embedded/bin``` rather than via the standard ```#!/usr/bin/env ruby```

**Comment by vkakhnych** [comment]
In my case works with RVM only if in /etc/default/sensu:

GEM_HOME=/opt/sensu/embedded/lib/ruby/gems/2.0.0
GEM_PATH=/opt/sensu/embedded/lib/ruby/gems/2.0.0
