### ISSUE TITLE
Support basic wildcard searches for clients in the API

### ISSUE THREAD

**Issue by pstoll** [sensu/sensu#550]
This currently works to get events for a single client:
  curl  http://sensu.foo.com/clients/db3.cluster1

I'd like to have the API support some sort of wildcards. Since redis has globs handy with minimal work, how about:
  curl http://sensu.foo.com/clients/db\?.cluster1
or
  curl http://sensu.foo.com/clients/db\?.\*ster1

(command line escaping shown above)

And have it return all clients that match that pattern.

This could presumably be extended to support patterns anywhere. Ultimately I'd like to have this functionality exposed in the dashboards but I'll start w/ the API.

FWIW - I have code that does this. I'll pull together a PR.

**Comment by portertech** [comment]
A trello card has been created for this feature/functionality https://trello.com/c/KJXvO2j2/12-as-an-operator-i-would-like-the-sensu-api-to-provide-result-filters-eg-nested-attribute-foo

**Comment by calebhailey** [comment]
I would close this due to inactivity, but I think this is still a valid suggestion (and some more recent issues have made similar suggestions). I've tagged this issue to include this in a renewed discussion about overall API improvements (see #1220). Please watch that issue for activity and participate there if you have any further thoughts to share. #monitoringlove

**Comment by portertech** [comment]
Just merged https://github.com/sensu/sensu/pull/1595 into the 0.29 release branch, which implements generic GET response content filtering. Not going to implement URL regex params at this time.

**Comment by pstoll** [comment]
@portertech - I appreciate the follow up, thanks.
