### ISSUE TITLE
keepalive errors

### ISSUE THREAD

**Issue by MrPink** [sensu/sensu#717]
Hi,
I've been using Sensu a little while now but recently I've been seeing a lot of " No keep-alive sent from client in over 120 seconds" alerts.

Some background
Sensu version 0.12.6 running on a single Ubuntu 12.04.3 LTS AWS instance
rabbitmq-server    3.1.5-1 
Sensu-client 0.12.6 (We have Gentoo and Ubuntu clients but they are both having the same issue)

RabbitMQ is not clustered and is running locally on the Sensu server.

In my RabbitMQ logs I'm seeing the following
error on AMQP connection <0.725.0>: {ssl_upgrade_error,closed} (unknown POSIX error)

and also

connection_closed_abruptly

and sometimes

{amqp_error,not_found,"no queue 'keepalives' in vhost '/sensu'",

I've done some googling and come to a bit of a blank.

Any help/guidance would be great,

Thanks,

**Comment by paktek123** [comment]
I seem to be getting the same error and due to this error the sensu-api and sensu-server processes stop, in the sensu-server.log, I see

{"timestamp":"2015-03-19T21:51:16.574248+0000","level":"warn","message":"received signal","signal":"TERM"}

{"timestamp":"2015-03-19T21:51:16.596569+0000","level":"fatal","message":"transport connection error","error":"rabbitmq channel closed"}

it is probably something wrong with rabbit but should the server and api be going down if rabbitmq acts up? Is this by design?

**Comment by portertech** [comment]
@paktek123 a "rabbitmq channel closed" error usually indicates a "unrecoverable" RabbitMQ error, however, you can use the following configuration with 0.17 to recover from this error:

```
{
  "transport": {
    "reconnect_on_error": true
  }
}
```
