### ISSUE TITLE
Second host has ceased sending keepalives!

### ISSUE THREAD

**Issue by gwinans** [sensu/sensu#844]
The title says.

A sensu-client box has simply stopped sending keepalives. There's nothing in the logs, no errors... nothing. It just abruptly stopped sending keepalives about 8 hours ago. I've go so far has to flat out reboot both hosts and flushdb/flush all on the redis instance.

No bueno.

What else can I look at to get the second host to start delivering keepalive notices again?

Also, can we get some type of message in the logs that indicates delivery/failed delivery of keepalives?

**Comment by calebhailey** [comment]
@gwinans hi there! Sorry for the radio silence on this! I'm going to go ahead and close this due to inactivity (mostly on our part), and because I'm presuming you figured this out. Also, the sensu keepalive mechanism is one of the more critical components of the software, so if this was a widespread issue related to Sensu itself I'm certain we'd be overwhelmed with similar issues. Please feel free to open a new issue if this matter is not resolved. 

#monitoringlove
