### ISSUE TITLE
Default handler missing

### ISSUE THREAD

**Issue by soupdiver** [sensu/sensu#855]
I just have a fresh installation of sensu and  followed the **Getting Started* guide.
The docs say `Out of the box Sensu ships with a ‘default’ handler which does nothing more than parse the JSON its fed via STDIN and spits back to STDOUT.`
But when I copy the the check from the guide I get:
```
{"timestamp":"2015-02-01T08:37:31.834836+0100","level":"error","message":"unknown handler","handler_name":"default"}
```
So is the default handler missing or is it an error in the docs?
Also see: sensu/sensu-docs/issues/181

**Comment by calebhailey** [comment]
@soupdiver hi there! Sorry for the radio silence on this! 

There's never been very good documentation around the default handler, IMO, but we've tagged that for inclusion in the 0.23 docs (the current release), here: https://github.com/sensu/sensu-docs/issues/98 

Having said that, I'm going to go ahead and close this issue due to inactivity (mostly on our part) and track this effort on https://github.com/sensu/sensu-docs/issues/98. Please feel free to open a new issue if this matter is not resolved.

**Comment by Isorb0** [comment]
Sorry to open this again, we still have this issue on Sensu core 1.6.2, is it fixed in any docs?
