### ISSUE TITLE
Check dependencies on client keepalive

### ISSUE THREAD

**Issue by khuongdp** [sensu/sensu#861]
Hi

Is it possible to make my check_http depending on the client keepalive. I don't want to be notified if the site is down when the server is down.

**Comment by johntdyer** [comment]
Wow, that is funny, I literally came here to open this same ticket :)   

I totally agree w/ @khuongdp by default all checks should have a dependency on the keepalive check, but we shouldn't have to define these in all checks.  Is there any way to set a global default dependency on checks?

**Comment by warmfusion** [comment]
The keepalives send their heartbeats across the same channel your check results use; I don't understand how your server can fail to heartbeat but still report service events... How are your checks set up?

**Comment by portertech** [comment]
@warmfusion is correct, a client cannot produce check results if the keepalive event is valid (not caused by clock sync issues etc).

**Comment by hurrycaine** [comment]
What about with ttl now? I have not tried them yet but it sounds like you would get alerts from all checks that have a ttl if the server was down. It would be nice to just get the keepalive in that instance. Your keepalive threshold would have to be less than the individual ttl.

**Comment by portertech** [comment]
@hurrycaine good point, will investigate the best approach to exclude expire check TTLs for clients with keepalive events.

**Comment by jaxxstorm** [comment]
hi @portertech I have a different use case but the same request.

I have a check that pings the gateway of a datacenter, and I want to make my keepalives dependent on that. So:

keepalive -> depends -> check_dc1

This way I can avoid keepalive storms when I lose a network link. Is this possible?

**Comment by calebhailey** [comment]
Similar to #931. Tagging both with Feature labels for further consideration.

**Comment by jaxxstorm** [comment]
@calebhailey any love for this in future sensu versions?

**Comment by calebhailey** [comment]
@jaxxstorm we are definitely going to consider it. [Sensu Core version 0.26][0] is going to be all about a [major rethink of how events are subdued/silenced in Sensu][1] (e.g. during scheduled and unscheduled maintenance, in specific environments, etc), which is going to take the shape of a new [first-class "silence" API][2] (i.e. silencing built-in to Sensu instead of being a function of plugins/handlers leveraging a convention based on stashes). 

We have an internal design discussion scheduled for next week (after some of our team gets back from vacation and Monitorama) specifically to discuss if/how Sensu may be able to support silencing based on dependencies as a first-class feature. Although this is a popular request, in practice we find it difficult to recommend or design around because it requires a static (configuration-based) mapping of dependencies to dynamic infrastructure (i.e. where new systems register themselves and may be ephemeral). Historically, we've struggled with how to implement a first-class solution for this in Sensu because it's a bit like trying to cram "legacy thinking" into Sensu's more dynamic model. Having said that, _we are going to_ review all of the ideas that have been presented in recent months (including this issue) and trying to make a determination if there's a sufficiently dynamic way to do this that makes sense for Sensu (without killing performance). 

In the interim, what we may eventually consider to be "legacy" dependency filtering (i.e. via statically mapping dependencies) _is already available_ in Sensu Enterprise via a [built-in `check_dependencies` filter][3], which is provided via a Sensu filter extension in Sensu Enterprise (i.e. it's not just performing a simple attribute comparison; it does API look-ups). 

[0]:  https://github.com/sensu/sensu/milestones/0.26
[1]:  https://github.com/sensu/sensu/issues/1219#issuecomment-225245100
[2]:  https://github.com/sensu/sensu/issues/1328
[3]:  https://sensuapp.org/docs/latest/enterprise/filters/check-dependencies.html

**Comment by CVTJNII** [comment]
Maybe I'm not following this thread correctly but these dependencies are already a thing?

If you want a check to depend on the keepalive add "dependencies": [ "keepalive" ] to the check config.
If you want the keepalive to depend on something add "keepalive": { "dependencies": [ "something" ] } to the client config.

This of course just passes the dependencies through to something else, be it the new native filters or the old-style sensu-plugin, but that's a whole other issue.

Have I missed the thread here?

**Comment by portertech** [comment]
Check dependencies can be added to the client "keepalive", @CVTJNII is correct. This issue should have been closed when all "keepalive" nested attributes were added to the check result context. :+1:
