### ISSUE TITLE
sensu-0.17.0.beta.1-1 "client must be a hash"

### ISSUE THREAD

**Issue by electricJP** [sensu/sensu#897]
Hello,

Testing the latest build on a Win 2012 R2 server. I get the following error:

{"timestamp":"2015-03-16T13:14:22.871809-0400","level":"fatal","message":"invalid settings"}
{"timestamp":"2015-03-16T13:14:22.949945-0400","level":"fatal","message":"client must be a hash","object":null}
{"timestamp":"2015-03-16T13:14:22.949945-0400","level":"fatal","message":"SENSU NOT RUNNING!"}

sensu-0.14.0-1 is working fine with the same client.json:

{
"client": {
"name": "server_fqdn",
"address": "10.136.3.30",
"subscriptions": [ "Windows-servers" ]
}
}

Please note I removed the real FQDN.
Also note I did a version upgrade (not fresh install).

For reference, I also posted in sensu-build, so feel free to close one of the 2 issues.

Thank you by advance.

**Comment by portertech** [comment]
You may need to update your service config (XML), the log event shows the value as null, so it's not being read.

**Comment by electricJP** [comment]
Indeed, I didn't noticed that sensu-client.xml was replaced during the update. Thx for the help.

**Comment by julientheriaultlapresse** [comment]
I have this issue, but just to confirm, what needs to be changed in the XML file?

**Comment by portertech** [comment]
@julientheriaultlapresse the Sensu CLI arguments in the XML service config file must reflect the location of your Sensu configs etc.

**Comment by julientheriaultlapresse** [comment]
I have a Linux machine running the Sensu server.  Windows is a client only.  The "config.json" file contains the configuration pointing to the server.  This is my current XML file (on Windows), I haven't changed anything since the client installation :


<service>
  <id>sensu-client</id>
  <name>Sensu Client</name>
  <description>This service runs a Sensu client</description>
  <executable>C:\opt\sensu\embedded\bin\ruby</executable>
  <arguments>C:\opt\sensu\embedded\bin\sensu-client -l C:\opt\sensu\sensu-client.log</arguments>
</service>

**Comment by agoddard** [comment]
@julientheriaultlapresse it looks like you're missing the config file argument in the XML config, `-c C:\opt\sensu\config.json`

**Comment by portertech** [comment]
You can run `C:\opt\sensu\embedded\bin\ruby C:\opt\sensu\embedded\bin\sensu-client -h` for all available CLI arguments. You may also need `-d C:\opt\sensu\conf.d` for additional configuration files (directory).
