### ISSUE TITLE
Issue with TCP Streaming to client-socket

### ISSUE THREAD

**Issue by prasadbalpa** [sensu/sensu#904]
I have a sensu plugin for syslog which actually gets executed whenever there are events with high severity.  The sensu plugin creates a message from syslog message and then sends it over TCP to sensu-client on the same node(localhost).  If this is done at a high rate, the sensu-client fails to get the right message boundary and message is lost.  How do I configure sensu client to look for actual message boundary for incoming messages over TCP.  This is not an issue over UDP as it is based on datagram.

**Comment by ryancox** [comment]
Are you confident that the issue is related to throughput and not larger payloads getting split over multiple packets? 

I have not found sending large payloads to the 3030 socket to be reliable and resorted to splitting them up within the application prior to writing out to the socket.

The protocol has no foreknowledge of the payload size; versus for example HTTP chunking which first sends the number of octets to expect. 

Details:

https://github.com/sensu/sensu/blob/v0.17.1/lib/sensu/client/socket.rb#L43

Sensu's method relies instead on yajl-ruby's parse attempt failing with a ParseError. When TCP, this is understood to mean that the rest of the payload will arrive in a subsequent packet.

https://github.com/sensu/sensu/blob/v0.17.1/lib/sensu/client/socket.rb#L167

Unfortunately, this is not reliable, as certain types of partial JSON messages will fail to parse within yajl, but return a different type of error. ( Something as simple as '{"x":' )

**Comment by prasadbalpa** [comment]
Finally, finally, I figured that out.  It is just due to not waiting for a ack from sensu-client.  We were sending crit and warning msgs one after the other.  Sensu-client can take only one msg(JSON) @ a time, but we were flooding it...so, msgs were getting combined and getting messed up.  Now, I implemented a request->response kind of a plugin...send a msg and wait for ack from sensu-client. It works just fine.. Thank you for your help.
