### ISSUE TITLE
sensu-api post for check

### ISSUE THREAD

**Issue by mag009** [sensu/sensu#935]
Hi,

It would be nice to be able to dynamically create a check instead of restarting the daemon each time. - POST api for the check

any plan for this?

thanks!

**Comment by portertech** [comment]
@mag009 What will handle check dependencies (e.g. check plugin installation)? How would you handle versioning, if not leveraging an IaC (Configuration Management) workflow?

**Comment by mag009** [comment]
well I have a need where I'm doing api call of my inventory to generate a check in .json but everytime I generate these check(s) I have to manage the daemon.

I agree with you normal check are managed via puppet/chef etc.. but in this particular case what I'm building is for passive check(s) I'm executing remove check(s) to device like cisco switches , servers management interfaces , etc...  that's why it would make sense for these to be dynamically created. Those are maintained by an inventory/ api unless you have a better suggestion other then restarting the sensu-client each time I have a check that is created.

**Comment by mag009** [comment]
just to give you an idea I have a client with 2000 checks ( quering switches/mgmt interfaces where the sensu-agents cannot run etc..)  so I want to avoid restarting the client for this. I'm adding/remove check often.  Maybe it would be simpler to have a reload of the daemon ?

**Comment by szibis** [comment]
+1

**Comment by calebhailey** [comment]
@mag009 hi there! Sorry for the radio silence on this! 

This is an interesting issue, and one that @agoddard and I have discussed internally a bit recently. 

It seems to me like there could be an opportunity to support some sort of solution via the [`/request` API endpoint][1], which already provides the ability to override defined check "subscriptions" in the API request. It seems like the only drawback for extending this capability to allow other overrides would be for security purposes. 

@portertech I wonder if check [command token substitution][2] could be extended to support _check_ definition attributes in addition to _client_ definition attributes? For example: 

``` json
{
  "checks": {
    "example_check": {
      "command": "my_snmp_check.rb --host :::host|10.0.1.1:::",
      "publish": false,
      "subscribers": ["snmp_relay"]
    }
  }
}
```

If this was possible, we could extend the `/request` API to allow any custom attributes (and attribute overrides) to be provided in the API request, except maybe the `command` attribute - for obvious security purposes. In this case, if the example `my_snmp_check.rb` accepted a `--host` [command argument][3], you could override it in the API request like this: 

```
curl -s -i \
-X POST \
-H 'Content-Type: application/json' \
-d '{"check": "my_snmp_check", "host": "NEWHOST"}' \
http://127.0.0.1:4567/request
```

Thoughts? 

[1]: https://sensuapp.org/docs/latest/api-checks#the-request-api-endpoint 
[2]: https://sensuapp.org/docs/latest/checks#check-command-tokens 
[3]: https://sensuapp.org/docs/0.23/checks#check-command-arguments

**Comment by calebhailey** [comment]
I'm going to presumptively tag this for 0.24 to prompt some discussion over the next few weeks.

**Comment by calebhailey** [comment]
Related: https://github.com/sensu/sensu/issues/900

**Comment by calebhailey** [comment]
Potentially related: https://github.com/sensu/sensu/issues/864

**Comment by mag009** [comment]
wonderful!

**Comment by calebhailey** [comment]
I just realized that my proposed change to check command token substitution would be a breaking change. It would make it necessary to access client attributes with "dot notation" (e.g. `:::client.attribute:::`) rather than having "direct access" to the client attributes (e.g. `:::attribute:::`) requiring all existing check definitions using token substitution to be updated from "direct access" to "dot notation" (i.e. `:::attribute:::` would need to become `:::client.attribute:::`). This doesn't mean we can't do it, but it does mean we'll probably want to get a lot more eyes on any changes before we roll them out. 

:eyes:

**Comment by calebhailey** [comment]
@mag009 upon further discussion with @portertech on this, he explained the reason that my proposed solution doesn't already exist, as follows:

**Any changes to Sensu's behavior that would facilitate execution of arbitrary commands on a Sensu server (or another system) are a massive security risk**. The way check token substitution works today only allows for a potentially compromised Sensu client to override command execution on the local system (which a potential attacker wouldn't need Sensu for if they had already compromised the system), so there's almost no risk exposure. Check command token substitution is safe because the only tokens that can be substituted are coming from the same system where the commands are executed. 

It is for this same reason that the [`/request` API][1] is locked down such that it only supports requests for predefined checks (by check name) and predefined subscriptions (by subscription name). Support for executing commands (i.e. subscription checks) that aren't already defined on the sensu-server, and/or for targeting systems that have not themselves joined a predefined subscription would open similar security risks as mentioned above (i.e. allowing an attacker to execute commands on other systems). 

The thing you're trying to accomplish is possible, but it would require development of a custom plugin. You could do the _"api call of [your] inventory"_ in a plugin, and then have the plugin execute a service check against each external system/device, and then publish unique results for each system/device using the new [Results API (POST)][2] (setting a unique `source` attribute for each result, so that Sensu will create a [proxy client][3] for each distinct system/device).

I hope this all makes sense. I'm going to go ahead and close this issue since the original request is for using the `/request` API in ways that we cannot support for security purposes. Having said that, please feel free to submit a new issue if this matter is not resolved. 

[1]: https://sensuapp.org/docs/latest/api-checks#the-request-api-endpoint 
[2]: https://sensuapp.org/docs/latest/api-results#results-post 
[3]: https://sensuapp.org/docs/latest/clients#proxy-clients
