### ISSUE TITLE
Any reasons why thin and uuidtools are not the latest?

### ISSUE THREAD

**Issue by darix** [sensu/sensu#966]
And as a follow up question would any rack capable web server be able to run sensu? (e.g. unicorn/puma)

**Comment by darix** [comment]
This might do for eventmachine:
```
s.add_dependency "eventmachine", RUBY_PLATFORM =~ /mingw/i ? "1.0.3"  : "~> 1.0.3"
```

**Comment by portertech** [comment]
@darix the Sensu API uses EventMachine and requires an evented web server, thin. The Sensu project is very specific about the versions of libraries that it requires, for consistency between installs, and to provide a stable/reliable service. As for the EventMachine version lock, it's for Windows, as that's the latest version with a working compiled binary. Work is being done to get sensu-em to compile on Windows using devkit, so that the EventMachine version lock can be removed as it will no longer be used.

**Comment by portertech** [comment]
Pushing 0.19.1-1 to the repositories, the build includes the latest thin and uuidtools :+1:
