### ISSUE TITLE
Variable replacements with event data.

### ISSUE THREAD

**Issue by magmax** [sensu/sensu#979]
There should be a way to customize a check with the event data. I'm not sure if the best place is the core or Uchiwa, but I finally decide by core.

Imagine you have a generic subscription, like "linux". Any linux is going to use it. And you want to show a link to some resource, customized for that host, for example, a grafana image. Something like:
    "http://example.org/render?whatever=whatever&var-host={{ hostname }}"
So each subscribed host should replace the variable in order to customize the URL:
    "http://example.org/render?whatever=whatever&var-host=host_1"
    "http://example.org/render?whatever=whatever&var-host=host_2"

Possible usages:
- playbooks customization.
- grafana images customization.
- e-mail data customization.

I thought in making a mutator, but as long as mutators cannot be stacked (just one can be run for a handler), I think it is not the solution.

Please, maybe this is already working, but I searched and didn't find anything in documentation.

**Comment by cixelsyd** [comment]
I asked a question in the sensu IRC channel last week that I believe is related: "how do I set custom thresholds, per host, for standard checks so that I can set diskspace to 10% on hostA and diskspace to 20% on hostB?"

The answer came back, "check command token substitution," located current at an old document page (but still included in the current sensu distro):

https://sensuapp.org/docs/0.16/checks#check-command-token-substitution

For your case, I'd add a custom token to either the check or the client definition, and fill it with the values that I needed.  I'm currently using chef to create the sensu configurations everywhere, so its simple to fill the value of the token in programmatically.  Perhaps this helps?

**Comment by magmax** [comment]
Sure!

Thank you very much!
