### ISSUE TITLE
Abort startup on invalid json files

### ISSUE THREAD

**Issue by maticmeznar** [sensu/sensu#987]
Right now, Sensu logs a warning, skips any invalid json files and continuous the startup procedure. If an extension/plugin depends on that json file, the extension will fail to load with a cryptic error like:
``/etc/sensu/extensions/handlers/relay.rb:184:in `post_init': undefined method `keys' for nil:NilClass (NoMethodError)``

I propose that Sensu immediately stops the startup procedure when it encounters an invalid json file, so the json parsing error is the last error in the log file, making the problem easier to detect and solve.

**Comment by portertech** [comment]
We should run a public poll for this, as Sensu used to stop/exit when it encountered any sort of loading or configuration error, but the community has since pushed it in the other direction, in favor of more resiliency over clarity and correctness.

**Comment by maticmeznar** [comment]
IMO, if you have a .json file in /etc/sensu, you want it to load. Your desire to do so is clear by putting a file there. It makes no sense for Sensu to start, if it cannot load all the files the sysadmin wants to load. Sensu would be in an unexpected state, deviating from the presumed state and the only way the sysadmin can know this is if he looks at the logs.

I'd like to either have the default behavior changed or an option in /etc/default/sensu .

**Comment by calebhailey** [comment]
@maticmeznar hi there! Sorry for the radio silence! 

I wonder if the new [`--pring_config` CLI option][1] in [Sensu 0.23][2] would help alleviate this issue? With this new CLI option it's possible to ask Sensu to compile configuration and then quit, outputting the compiled configuration to STDOUT. It seems like you could use this option to test configuration changes before restarting the Sensu server process and achieve your desired behavior. 

I'm going to close this issue due to inactivity (mostly on our part, but also assuming you've resolved this issue). Please feel free to create a new issue if this matter isn't resolved. 

#monitoringlove 

[1]: https://sensuapp.org/docs/latest/configuration#sensu-service-cli-arguments
[2]: https://sensuapp.org/docs/0.23/changelog

**Comment by calebhailey** [comment]
Oops, ignore that reference - I pasted the wrong link. :)
