### ISSUE TITLE
Check API not listing checks

### ISSUE THREAD

**Issue by sstarcher** [sensu/sensu#989]
All of my checks are defined at the server.  My servers all get the checks they are subscribed for, but when asking the sensu api sensu:4567/checks I get '[]'.

Hitting other API endpoints like /clients works properly.

Uchiwa shows everything also except for the Checks tab is entirely empty, but if I click on a client and click on a check under the client I see all of the correct data.

Sensu 0.19.2
Uchiwa 0.10.1

**Comment by portertech** [comment]
Did you restart the API to pick up the latest configuration changes? i.e. checks

**Comment by sstarcher** [comment]
@portertech we restart client, server, and api every time we change the files

**Comment by portertech** [comment]
@sstarcher does the Sensu API log show any configuration loading errors at startup?

**Comment by sstarcher** [comment]
No errors at all

```
api_1 | {"timestamp":"2015-07-08T18:03:09.612243+0000","level":"warn","message":"loading config files from directory","directory":"/etc/sensu/conf.d"}
api_1 | {"timestamp":"2015-07-08T18:03:09.612359+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/rabbitmq.json"}
api_1 | {"timestamp":"2015-07-08T18:03:09.612418+0000","level":"warn","message":"loading config file","file":"/etc/sensu/conf.d/redis.json"}
api_1 | {"timestamp":"2015-07-08T18:03:09.612493+0000","level":"warn","message":"config file applied changes","file":"/etc/sensu/conf.d/redis.json","changes":{"redis":[null,{"host":"redis.service.consul","port":6379}]}}
```

**Comment by portertech** [comment]
@sstarcher looks like the API log doesn't show it loading check definition configuration files.

**Comment by sstarcher** [comment]
I'm only loading the checks into the server. Do they also need loaded into
the api?

**Comment by calebhailey** [comment]
@sstarcher hi there. Sorry for the radio silence on this issue. I'm assuming you've figured this out by now, but if not (or if you aren't aware of this relatively new resource), we've since documented how Sensu configuration works in pretty significant detail: https://sensuapp.org/docs/latest/configuration 

We've also added [a new CLI option called `--pring_config` in Sensu 0.23][1] that will help troubleshoot configuration issues like this, which allows you to view the compiled configuration for a Sensu process. 

I'm going to go ahead an presumptively close this issue, but please feel free to open a new issue if this matter isn't resolved. 

#monitoringlove 

[1]: https://sensuapp.org/docs/latest/configuration#sensu-service-cli-arguments
