### ISSUE TITLE
Subdue publisher vs Handlers

### ISSUE THREAD

**Issue by johntdyer** [sensu/sensu#997]
Hello,

 The docs are not clear on the differences between subduing at the handlers or the publisher.  ( https://sensuapp.org/docs/latest/checks ).  Can you please elaborate when one would use one or the other ? 

Thanks

-John

**Comment by portertech** [comment]
Subduing at the publisher stops check requests from being published for the period of time. Subduing at the handler stops event handling for the period of time.

**Comment by johntdyer** [comment]
Thanks what I sort of figured but I am not having much luck implementing it on a keep alive.   Any chance u have an example showing a keep alive being subdued on the publisher during evenings and weekends?  

Thanks

**Comment by johntdyer** [comment]
@portertech  - So here is my keepalive / client as shown in Uchiwa 

http://drops.johntdyer.com/HhrH/5vaHHaW0

Right now the check is still failing and the only way I am able to keep the handler from handling the event is to create a stash.   Am I doing something wrong here?

-John

**Comment by portertech** [comment]
You want to subdue `"at": "handler"`.

**Comment by johntdyer** [comment]
When would I want to use publisher ?

**Comment by calebhailey** [comment]
Tagged this for renewed discussion around a subdue redux; see #1219

**Comment by calebhailey** [comment]
This is fixed by #1415, which is included in version 0.26, which is now in the unstable repos (should be released tomorrow). 

Subdue rules now apply to check publishing, **ONLY** (not to handlers). Time-based rules for handlers are now supported via a new filter `when` attribute. See #1415 for more information, or the impending 0.26 release notes.
